### ISSUE TITLE
GitHub org user removed webhook server exception

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1237]
## Issue - Bug

Reproduction steps:

1. Add test repo belonging to a GitHub org to a Parabol team with linked user Jordan
2. Create new issue assigned to Jordan from Parabol team dashboard
3. Remove Jordan from GitHub org on GitHub
4. Expect that Jordan is unlinked from repo (and that card is archived)

Observed:

```
2017-08-11T00:08:32.484205058Z app[web.1]: (node:245) TypeError: Data must be a string or a buffer
2017-08-11T00:08:32.484239805Z app[web.1]:     at Hmac.update (crypto.js:97:16)
2017-08-11T00:08:32.484244345Z app[web.1]:     at signPayload (/app/src/server/utils/signPayload.js:6:6)
2017-08-11T00:08:32.484247838Z app[web.1]:     at _callee$ (/app/src/server/integrations/handleGitHubWebhooks.js:42:24)
2017-08-11T00:08:32.484251334Z app[web.1]:     at tryCatch (/app/node_modules/cashay/node_modules/regenerator-runtime/runtime.js:63:40)
2017-08-11T00:08:32.484273926Z app[web.1]:     at Generator.invoke [as _invoke] (/app/node_modules/cashay/node_modules/regenerator-runtime/runtime.js:337:22)
2017-08-11T00:08:32.484279042Z app[web.1]:     at Generator.prototype.(anonymous function) [as next] (/app/node_modules/cashay/node_modules/regenerator-runtime/runtime.js:96:21)
2017-08-11T00:08:32.484282598Z app[web.1]:     at step (/app/src/server/integrations/handleGitHubWebhooks.js:25:191)
2017-08-11T00:08:32.484286090Z app[web.1]:     at /app/src/server/integrations/handleGitHubWebhooks.js:25:437
2017-08-11T00:08:32.484291864Z app[web.1]:     at Promise (<anonymous>)
2017-08-11T00:08:32.484295613Z app[web.1]:     at /app/src/server/integrations/handleGitHubWebhooks.js:25:99
2017-08-11T00:08:32.484299141Z app[web.1]:     at /app/src/server/integrations/handleGitHubWebhooks.js:122:18
2017-08-11T00:08:32.484302657Z app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
...
`

**Comment by mattkrick** [comment]
fixed
