### ISSUE TITLE
Failed post-meeting email

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1291]
When wrapping up the meeting, i get this in the server console:
```
(node:8965) Error: Cannot automatically buffer without a document
    at injectGeneratedCSSOnce (/home/matt/code/action3/node_modules/aphrodite-local-styles/lib/inject.js:161:23)
    at injectStyleOnce (/home/matt/code/action3/node_modules/aphrodite-local-styles/lib/inject.js:178:9)
    at injectAndGetClassName (/home/matt/code/action3/node_modules/aphrodite-local-styles/lib/inject.js:254:5)
    at css (/home/matt/code/action3/node_modules/aphrodite-local-styles/lib/no-important.js:21:46)
    at Hashtag (/home/matt/code/action3/src/universal/components/ProjectEditor/Hashtag.js:11:50)
    at /home/matt/code/action3/node_modules/react-dom/lib/ReactCompositeComponent.js:305:16
```

this is true on the prod server, as well as on dev & local.

The reason is because the SummaryEmail.js component was artfully crafted by Terry to avoid using aphrodite in able to ensure that it can be processed on the server & looks good in the email. 
when we switched to draftjs, it looks like a dependency that uses aphrodite snuck in.
When could handle this if we created a vdom, or rewrote our aprhodite fork to handle SSR, or just eliminate that bit of breaking code. the first step is triage.

**Comment by mattkrick** [comment]
well that was easy. the problem is, in this instance, with Hashtag.js, which is the component that styles our beautiful components like `#private`.

So, we've got 2 choices:
- Rewrite all decorators to use inline styles
- Write a 2nd set of decorators that use inline styles & use those for crafting the email.

So, do we go for a minor performance hit, or a major duplication of efforts?
For now, I'm gonna take the hit. If the day comes when we have CRAZY styles for some decorator, we can take it on a case-by-case basis.
