### ISSUE TITLE
Cannot read property 'emit' of null [epic6.5]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1298]
## Issue - Bug

Repro steps:

1. Authenticate with github (that is to say, log into github.com)
1. On `action-staging` try to add the GitHub integration
1. Observe error

![image](https://user-images.githubusercontent.com/103000/29676763-f05838aa-88c6-11e7-9984-0496c7074c17.png)

**Comment by mattkrick** [comment]
golly, this is a tricky one.
i got to repro this the very first time i tried, but i couldn't do it again.
Checking out the logs, I see:
```
(node:244) TypeError: Cannot read property 'isActive' of null
2017-08-24T18:49:37.923099770Z app[web.1]:     at _callee3$ (/app/src/server/safeMutations/addProviderGitHub.js:109:20)
2017-08-24T18:49:37.923166724Z app[web.1]:     at tryCatch (/app/node_modules/cashay/node_modules/regenerator-runtime/runtime.js:63:40)
2017-08-24T18:49:37.923183552Z app[web.1]:     at Generator.invoke [as _invoke] (/app/node_modules/cashay/node_modules/regenerator-runtime/runtime.js:337:22)
2017-08-24T18:49:37.923191315Z app[web.1]:     at Generator.prototype.(anonymous function) [as next] (/app/node_modules/cashay/node_modules/regenerator-runtime/runtime.js:96:21)
2017-08-24T18:49:37.923199085Z app[web.1]:     at step (/app/src/server/safeMutations/addProviderGitHub.js:47:191)
2017-08-24T18:49:37.923206234Z app[web.1]:     at /app/src/server/safeMutations/addProviderGitHub.js:47:361
2017-08-24T18:49:37.923262226Z app[web.1]:     at <anonymous>
2017-08-24T18:49:37.923270711Z app[web.1]: (node:244) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

so, i fixed that bug & we'll see if that was what caused it.

**Comment by mattkrick** [comment]
this was still caused when you log out & log back in.
reason why is because we weren't setting the environment back to http.
fixed in notify branch
