### ISSUE TITLE
TypeError: Cannot read property 'getLength' of undefined

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1312]
https://sentry.io/parabol/action-production/issues/339304805/

```
TypeError: Cannot read property 'getLength' of undefined
  at default (./universal/utils/draftjs/truncateCard.js:38:21)
  at Component (./universal/modules/email/components/Card/Card.js:46:23)
  at _constructComponentWithoutOwner (../node_modules/react-dom/lib/ReactCompositeComponent.js:308)
  at _constructComponent (../node_modules/react-dom/lib/ReactCompositeComponent.js:284)
  at mountComponent (../node_modules/react-dom/lib/ReactCompositeComponent.js:187)
...
(45 additional frame(s) were not displayed)
```

**Comment by jordanh** [comment]
Context of bug:

- @tayamueller and me created a number of cards during our meeting
- I believe this occurred while ending the meeting

**Comment by mattkrick** [comment]
Oh this is really, really good.
Converting a card to plaintext adds in line breaks, so the character count is greater than it would be if you loop through each block & count the characters. the magical thing is that you stumbled upon this with a card with the perfect number of characters where that made a difference.
