### ISSUE TITLE
sendSegmentEvent exception, TypeError: Object.values is not a function

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1320]
## Issue - Bug

This is why our meeting events aren't being sent. Also of note, it looks like sentry isn't getting exceptions...

```
2017-09-01T17:33:48.710088568Z app[web.1]: (node:248) TypeError: Object.values is not a function
2017-09-01T17:33:48.710195594Z app[web.1]:     at _callee$ (/app/src/universal/utils/resolvePromiseObj.js:10:27)
2017-09-01T17:33:48.710202926Z app[web.1]:     at tryCatch (/app/node_modules/cashay/node_modules/regenerator-runtime/runtime.js:63:40)
2017-09-01T17:33:48.710207513Z app[web.1]:     at GeneratorFunctionPrototype.invoke [as _invoke] (/app/node_modules/cashay/node_modules/regenerator-runtime/runtime.js:337:22)
2017-09-01T17:33:48.710211983Z app[web.1]:     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/app/node_modules/cashay/node_modules/regenerator-runtime/runtime.js:96:21)
2017-09-01T17:33:48.710216631Z app[web.1]:     at step (/app/src/universal/utils/resolvePromiseObj.js:7:191)
2017-09-01T17:33:48.710220716Z app[web.1]:     at /app/src/universal/utils/resolvePromiseObj.js:7:437
2017-09-01T17:33:48.710224829Z app[web.1]:     at /app/src/universal/utils/resolvePromiseObj.js:7:99
2017-09-01T17:33:48.710228834Z app[web.1]:     at resolvePromiseObj (/app/src/universal/utils/resolvePromiseObj.js:8:7)
2017-09-01T17:33:48.710232839Z app[web.1]:     at getSegmentProps (/app/src/server/utils/sendSegmentEvent.js:25:10)
2017-09-01T17:33:48.710236949Z app[web.1]:     at _callee$ (/app/src/server/utils/sendSegmentEvent.js:33:36)
2017-09-01T17:33:48.710240918Z app[web.1]:     at tryCatch (/app/node_modules/cashay/node_modules/regenerator-runtime/runtime.js:63:40)
2017-09-01T17:33:48.710245036Z app[web.1]:     at GeneratorFunctionPrototype.invoke [as _invoke] (/app/node_modules/cashay/node_modules/regenerator-runtime/runtime.js:337:22)
2017-09-01T17:33:48.710254519Z app[web.1]:     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/app/node_modules/cashay/node_modules/regenerator-runtime/runtime.js:96:21)
2017-09-01T17:33:48.710258868Z app[web.1]:     at step (/app/src/server/utils/sendSegmentEvent.js:25:191)
2017-09-01T17:33:48.710262718Z app[web.1]:     at /app/src/server/utils/sendSegmentEvent.js:25:437
2017-09-01T17:33:48.710266676Z app[web.1]:     at /app/src/server/utils/sendSegmentEvent.js:25:99
2017-09-01T17:33:48.710270608Z app[web.1]:     at sendSegmentEvent (/app/src/server/utils/sendSegmentEvent.js:31:7)
2017-09-01T17:33:48.710274593Z app[web.1]:     at _callee$ (/app/src/server/graphql/models/Team/endMeeting/endMeeting.js:104:5)
2017-09-01T17:33:48.710278891Z app[web.1]:     at tryCatch (/app/node_modules/cashay/node_modules/regenerator-runtime/runtime.js:63:40)
2017-09-01T17:33:48.710283093Z app[web.1]:     at GeneratorFunctionPrototype.invoke [as _invoke] (/app/node_modules/cashay/node_modules/regenerator-runtime/runtime.js:337:22)
2017-09-01T17:33:48.710324284Z app[web.1]:     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/app/node_modules/cashay/node_modules/regenerator-runtime/runtime.js:96:21)
2017-09-01T17:33:48.710330973Z app[web.1]:     at step (/app/src/server/graphql/models/Team/endMeeting/endMeeting.js:37:191)
2017-09-01T17:33:48.710334761Z app[web.1]:     at /app/src/server/graphql/models/Team/endMeeting/endMeeting.js:37:361
```

- **Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
is our node version that old in production!?!

**Comment by mattkrick** [comment]
oh holy cow, 6.11.2. we need to bump that ASAP

**Comment by jordanh** [comment]
Yes, let's do it today. I think that's controlled in dokku by a `package.json` key... Let me look into it.

**Comment by jordanh** [comment]
It looks like updating to v0.8.4 isn't going to be a gimme.

```
ERROR in ./universal/styles/theme/appTheme.js
[1] Module not found: Error: Can't resolve 'appTheme.json' in '/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/universal/styles/theme'
```

Something is going on here that's causing our theme json not to be created. I can reproduce this locally too. I'm going to have a deeper look into it when I get back from lunch.
