### ISSUE TITLE
8.5 - Notification not found

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#1592]
```
2017-12-21T17:14:08.201193344Z app[web.1]: DEBUG GraphQL Error: [ { Error: Notification not found!
2017-12-21T17:14:08.201250522Z app[web.1]:     at requireNotificationOwner (/app/src/server/utils/authorization.js:155:9)
2017-12-21T17:14:08.201257379Z app[web.1]:     at _callee$ (/app/src/server/graphql/mutations/acceptTeamInviteNotification.js:23:5)
2017-12-21T17:14:08.201261259Z app[web.1]:     at tryCatch (/app/node_modules/cashay/node_modules/regenerator-runtime/runtime.js:63:40)
2017-12-21T17:14:08.201264653Z app[web.1]:     at Generator.invoke [as _invoke] (/app/node_modules/cashay/node_modules/regenerator-runtime/runtime.js:337:22)
2017-12-21T17:14:08.201268368Z app[web.1]:     at Generator.prototype.(anonymous function) [as next] (/app/node_modules/cashay/node_modules/regenerator-runtime/runtime.js:96:21)
2017-12-21T17:14:08.201271899Z app[web.1]:     at step (/app/src/server/graphql/mutations/acceptTeamInviteNotification.js:25:191)
2017-12-21T17:14:08.201275109Z app[web.1]:     at /app/src/server/graphql/mutations/acceptTeamInviteNotification.js:25:361
2017-12-21T17:14:08.201278230Z app[web.1]:     at <anonymous>
2017-12-21T17:14:08.201281920Z app[web.1]:     message: 'Notification not found!',
2017-12-21T17:14:08.201285021Z app[web.1]:     locations: [ [Object] ],
2017-12-21T17:14:08.201288171Z app[web.1]:     path: [ 'acceptTeamInviteNotification' ] } ]
```

On the client, it says 
```
{_error: "Cannot read property 'dataloader' of undefined"}
```

**Comment by mattkrick** [comment]
The `dataloder of undefined` thing is expected anytime there is a bug thanks to #1539
