### ISSUE TITLE
Agenda nav bug

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1660]
## Bug

No concrete reproduction steps on this one yet. @ackernaut has seen it too.

### How it manifests

When you are the facilitator and you click on

![image](https://user-images.githubusercontent.com/103000/35288935-d98795f0-001a-11e8-8aab-5423418742c6.png)

The UI advances to the next agenda item and then "bounces" back to the previous item. The only way to advance is by clicking the next item from the agenda list.

**Comment by jordanh** [comment]
![image](https://user-images.githubusercontent.com/103000/35288337-46e18900-0019-11e8-8f4a-d700fdc0e37a.png)

**Comment by jordanh** [comment]
Still seeing it, even though I refreshed.

**Comment by jordanh** [comment]
Possible related server trace:

```
2018-01-23T17:43:12.065297347Z app[web.1]: DEBUG GraphQL Error: [ { TypeError: Cannot read property 'id' of null
2018-01-23T17:43:12.065331907Z app[web.1]:     at _callee$ (/app/src/server/graphql/mutations/moveMeeting.js:127:61)
2018-01-23T17:43:12.065339180Z app[web.1]:     at tryCatch (/app/node_modules/cashay/node_modules/regenerator-runtime/runtime.js:63:40)
2018-01-23T17:43:12.065345893Z app[web.1]:     at Generator.invoke [as _invoke] (/app/node_modules/cashay/node_modules/regenerator-runtime/runtime.js:337:22)
2018-01-23T17:43:12.065363742Z app[web.1]:     at Generator.prototype.(anonymous function) [as next] (/app/node_modules/cashay/node_modules/regenerator-runtime/runtime.js:96:21)
2018-01-23T17:43:12.065371680Z app[web.1]:     at step (/app/src/server/graphql/mutations/moveMeeting.js:37:191)
2018-01-23T17:43:12.065377500Z app[web.1]:     at /app/src/server/graphql/mutations/moveMeeting.js:37:361
2018-01-23T17:43:12.065383518Z app[web.1]:     at <anonymous>
2018-01-23T17:43:12.065389943Z app[web.1]:     message: 'Cannot read property \'id\' of null',
2018-01-23T17:43:12.065396697Z app[web.1]:     locations: [ [Object] ],
2018-01-23T17:43:12.065402617Z app[web.1]:     path: [ 'moveMeeting' ] } ]
2018-01-23T17:43:12.845600314Z app[web.1]: DEBUG GraphQL Error: [ { TypeError: Cannot read property 'id' of null
2018-01-23T17:43:12.845626771Z app[web.1]:     at _callee$ (/app/src/server/graphql/mutations/moveMeeting.js:127:61)
2018-01-23T17:43:12.845631618Z app[web.1]:     at tryCatch (/app/node_modules/cashay/node_modules/regenerator-runtime/runtime.js:63:40)
2018-01-23T17:43:12.845635753Z app[web.1]:     at Generator.invoke [as _invoke] (/app/node_modules/cashay/node_modules/regenerator-runtime/runtime.js:337:22)
2018-01-23T17:43:12.845639833Z app[web.1]:     at Generator.prototype.(anonymous function) [as next] (/app/node_modules/cashay/node_modules/regenerator-runtime/runtime.js:96:21)
2018-01-23T17:43:12.845644163Z app[web.1]:     at step (/app/src/server/graphql/mutations/moveMeeting.js:37:191)
2018-01-23T17:43:12.845647743Z app[web.1]:     at /app/src/server/graphql/mutations/moveMeeting.js:37:361
2018-01-23T17:43:12.845651354Z app[web.1]:     at <anonymous>
2018-01-23T17:43:12.845672941Z app[web.1]:     message: 'Cannot read property \'id\' of null',
2018-01-23T17:43:12.845678363Z app[web.1]:     locations: [ [Object] ],
2018-01-23T17:43:12.845681979Z app[web.1]:     path: [ 'moveMeeting' ] } ]
```
