### ISSUE TITLE
User unable to login

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1679]
## Issue - Bug

Bug reported from the field. A user is trying to login to Parabol and is getting a white screen. I am guess that an exception is occurring login.

![image](https://user-images.githubusercontent.com/103000/35419704-4d1e1a6e-01ee-11e8-89d6-960aefb2f81b.png)

User id is `auth0|5989d412c164ea2039b466a4`

I'm opening this issue to track.

- **OS:** macOS 
- **Browser:** Safari

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Server exception:

```
2018-01-26T00:43:38.591334011Z app[web.1]: DEBUG GraphQL Error: [ { TypeError: The loader.load() function must be called with a value,but got: undefined.
2018-01-26T00:43:38.591372417Z app[web.1]:     at DataLoader.load (/app/node_modules/dataloader/index.js:44:13)
2018-01-26T00:43:38.591378011Z app[web.1]:     at resolve (/app/src/server/graphql/types/NotifyTeamInvite.js:16:40)
2018-01-26T00:43:38.591382506Z app[web.1]:     at resolveFieldValueOrError (/app/node_modules/graphql/execution/execute.js:544:18)
2018-01-26T00:43:38.591386841Z app[web.1]:     at resolveField (/app/node_modules/graphql/execution/execute.js:508:16)
2018-01-26T00:43:38.591391199Z app[web.1]:     at /app/node_modules/graphql/execution/execute.js:357:18
2018-01-26T00:43:38.591395546Z app[web.1]:     at Array.reduce (<anonymous>)
2018-01-26T00:43:38.591400097Z app[web.1]:     at executeFields (/app/node_modules/graphql/execution/execute.js:354:42)
2018-01-26T00:43:38.591404257Z app[web.1]:     at collectAndExecuteSubfields (/app/node_modules/graphql/execution/execute.js:799:10)
2018-01-26T00:43:38.591408244Z app[web.1]:     at completeObjectValue (/app/node_modules/graphql/execution/execute.js:781:10)
2018-01-26T00:43:38.591412336Z app[web.1]:     at completeAbstractValue (/app/node_modules/graphql/execution/execute.js:739:10)
2018-01-26T00:43:38.591416356Z app[web.1]:     at completeValue (/app/node_modules/graphql/execution/execute.js:672:12)
2018-01-26T00:43:38.591420266Z app[web.1]:     at completeValueWithLocatedError (/app/node_modules/graphql/execution/execute.js:595:21)
2018-01-26T00:43:38.591424357Z app[web.1]:     at completeValueCatchingError (/app/node_modules/graphql/execution/execute.js:570:21)
2018-01-26T00:43:38.591428379Z app[web.1]:     at resolveField (/app/node_modules/graphql/execution/execute.js:510:10)
2018-01-26T00:43:38.591432391Z app[web.1]:     at /app/node_modules/graphql/execution/execute.js:357:18
2018-01-26T00:43:38.591436361Z app[web.1]:     at Array.reduce (<anonymous>)
2018-01-26T00:43:38.591454294Z app[web.1]:     at executeFields (/app/node_modules/graphql/execution/execute.js:354:42)
2018-01-26T00:43:38.591458372Z app[web.1]:     at collectAndExecuteSubfields (/app/node_modules/graphql/execution/execute.js:799:10)
2018-01-26T00:43:38.591461956Z app[web.1]:     at completeObjectValue (/app/node_modules/graphql/execution/execute.js:781:10)
2018-01-26T00:43:38.591465612Z app[web.1]:     at completeValue (/app/node_modules/graphql/execution/execute.js:677:12)
2018-01-26T00:43:38.591469196Z app[web.1]:     at completeValueWithLocatedError (/app/node_modules/graphql/execution/execute.js:595:21)
2018-01-26T00:43:38.591472804Z app[web.1]:     at completeValueCatchingError (/app/node_modules/graphql/execution/execute.js:570:21)
2018-01-26T00:43:38.591476436Z app[web.1]:     at /app/node_modules/graphql/execution/execute.js:701:25
2018-01-26T00:43:38.591480041Z app[web.1]:     at Array.forEach (<anonymous>)
2018-01-26T00:43:38.591483691Z app[web.1]:     at forEach (/app/node_modules/iterall/index.js:336:25)
2018-01-26T00:43:38.591487122Z app[web.1]:     at completeListValue (/app/node_modules/graphql/execution/execute.js:697:24)
2018-01-26T00:43:38.591491854Z app[web.1]:     at completeValue (/app/node_modules/graphql/execution/execute.js:660:12)
2018-01-26T00:43:38.591495587Z app[web.1]:     at completeValueWithLocatedError (/app/node_modules/graphql/execution/execute.js:595:21)
2018-01-26T00:43:38.591499102Z app[web.1]:     at completeValueCatchingError (/app/node_modules/graphql/execution/execute.js:570:21)
2018-01-26T00:43:38.591502737Z app[web.1]:     at resolveField (/app/node_modules/graphql/execution/execute.js:510:10)
2018-01-26T00:43:38.591506186Z app[web.1]:     at /app/node_modules/graphql/execution/execute.js:357:18
2018-01-26T00:43:38.591509712Z app[web.1]:     at Array.reduce (<anonymous>)
2018-01-26T00:43:38.591513386Z app[web.1]:     at executeFields (/app/node_modules/graphql/execution/execute.js:354:42)
2018-01-26T00:43:38.591516836Z app[web.1]:     at collectAndExecuteSubfields (/app/node_modules/graphql/execution/execute.js:799:10)
2018-01-26T00:43:38.591520306Z app[web.1]:     at completeObjectValue (/app/node_modules/graphql/execution/execute.js:781:10)
2018-01-26T00:43:38.591523746Z app[web.1]:     at completeValue (/app/node_modules/graphql/execution/execute.js:677:12)
2018-01-26T00:43:38.591527259Z app[web.1]:     at /app/node_modules/graphql/execution/execute.js:634:14
2018-01-26T00:43:38.591530709Z app[web.1]:     at <anonymous>
2018-01-26T00:43:38.591534311Z app[web.1]:     message: 'The loader.load() function must be called with a value,but got: undefined.',
2018-01-26T00:43:38.591537984Z app[web.1]:     locations: [ [Object] ],
2018-01-26T00:43:38.591541362Z app[web.1]:     path: [ 'viewer', 'notifications', 'edges', 0, 'node', 'inviter' ] } ]
```

**Comment by jordanh** [comment]
Old notifications weren't migrated to new data format, causing server exception. Old data was manually migrated by @mattkrick
