### ISSUE TITLE
Chore: trap staging stripe exception on acceptInvitation

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1711]
## Issue - Bug

When I perform a check on staging to accept an invitation by a user who exists on product, I hit the following server exception:

```
2018-02-01T02:17:45.727279702Z app[web.1]:     at errorObj (/app/src/server/utils/utils.js:7:34)
2018-02-01T02:17:45.727291359Z app[web.1]:     at _callee$ (/app/src/server/billing/stripe.js:12:11)
2018-02-01T02:17:45.727296189Z app[web.1]:     at tryCatch (/app/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
2018-02-01T02:17:45.727300604Z app[web.1]:     at Generator.invoke [as _invoke] (/app/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
2018-02-01T02:17:45.727305077Z app[web.1]:     at Generator.prototype.(anonymous function) [as throw] (/app/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
2018-02-01T02:17:45.727309542Z app[web.1]:     at step (/app/src/server/billing/stripe.js:21:191)
2018-02-01T02:17:45.727313771Z app[web.1]:     at /app/src/server/billing/stripe.js:21:402
2018-02-01T02:17:45.727317824Z app[web.1]:     at <anonymous>
2018-02-01T02:17:45.727338067Z app[web.1]:     message: '{"_error":"No such subscription: sub_B8l3Cr8Sug1AZO; a similar object exists in live mode, but a test mode key was used to make this request."}',
2018-02-01T02:17:45.727343991Z app[web.1]:     locations: [ [Object] ],
2018-02-01T02:17:45.727347714Z app[web.1]:     path: [ 'acceptTeamInviteEmail' ] } ]
```

This makes release integration testing harder than it needs to be. We should ignore this exception in the resolver and move on. Right now, the test user is unable to the team invitation and gets duckies forever.

- **OS:** Linux
- **Browser:** Chrome 
- **Node version:** v8.9.4
- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Test users can *which also exist as registered emails on production*:
   - can accept invitations

**Comment by jordanh** [comment]
Never prioritized. Not a big deal. Iceboxing for now.
