### ISSUE TITLE
TypeError: Cannot read property 'getDataID' of null

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#1873]
https://sentry.io/parabol/action-production/issues/490664298/

```
TypeError: Cannot read property 'getDataID' of null
  at updateTaskTaskUpdater (./universal/mutations/UpdateTaskMutation.js:48:52)
  at updater (./universal/subscriptions/TaskSubscription.js:87:11)
  at Set.forEach (<anonymous>)
  at apply (./universal/modules/teamDashboard/components/Team/Team.js:35:5)
  at Array.forEach (<anonymous>)
...
(20 additional frame(s) were not displayed)
```

**Comment by jordanh** [comment]
This one came up during a client on-boarding. I do not have good reproduction criteria for it other than:

1. We ran a meeting
2. I tried to show her how the search bar works to filter cards and typing in the bar did not filter cards
3. Then I said "click team settings" and she got this error

Let's keep 👀 to see if this one pops up again

**Comment by jordanh** [comment]
Scrubbed, no change

**Comment by jordanh** [comment]
Scrubbed, no change
