### ISSUE TITLE
Intermittent websocket trouble 

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#210]
## Issue - Bug

Not precisely sure what the cause is, but documenting this as a placeholder. If others encounter this in the wild, please add more info.

Observed after a user accepted an invitation, set their preferred user name, and redirected to the team-dashboard for the first time. When focusing on a project (causing a `cashay.mutate('edit')`) the following is emitted from the server console:

```
DEBUG GraphQL Error: [ { Error: {"_error":"this requires a websocket channel exchange"}
      at errorObj (utils.js:5:32)
      at requireWebsocketExchange (authorization.js:53:11)
      at _callee$ (presenceMutation.js:25:7)
      at tryCatch (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/regenerator-runtime/runtime.js:62:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/regenerator-runtime/runtime.js:336:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/regenerator-runtime/runtime.js:95:21)
      at step (presenceMutation.js:7:1)
      at presenceMutation.js:7:1
      at new Promise (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/core-js/modules/es6.promise.js:191:7)
      at presenceMutation.js:7:1
      at resolve (presenceMutation.js:23:77)
      at resolveOrError (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:447:12)
      at resolveField (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:438:16)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:219:20
      at run (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/core-js/modules/es6.promise.js:87:22)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/core-js/modules/es6.promise.js:100:28
      at flush (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/core-js/modules/_microtask.js:18:9)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
    message: '{"_error":"this requires a websocket channel exchange"}',
    locations: [Getter],
    path: [ 'edit' ] } ]
```

After clicking on the meeting lobby from the team dashboard:

```
DEBUG GraphQL Error: [ { Error: {"_error":"this must be called from a websocket"}
      at errorObj (utils.js:5:32)
      at requireWebsocket (authorization.js:47:11)
      at _callee3$ (teamMutation.js:114:7)
      at tryCatch (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/regenerator-runtime/runtime.js:62:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/regenerator-runtime/runtime.js:336:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/regenerator-runtime/runtime.js:95:21)
      at step (teamMutation.js:16:1)
      at teamMutation.js:16:1
      at new Promise (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/core-js/modules/es6.promise.js:191:7)
      at teamMutation.js:16:1
      at resolve (teamMutation.js:110:65)
      at resolveOrError (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:447:12)
      at resolveField (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:438:16)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:219:20
      at run (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/core-js/modules/es6.promise.js:87:22)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/core-js/modules/es6.promise.js:100:28
      at flush (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/core-js/modules/_microtask.js:18:9)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
    message: '{"_error":"this must be called from a websocket"}',
    locations: [Getter],
    path: [ 'startMeeting' ] } ]
```

- **OS:** OSX
- **Browser:** Chrome
- **Node version:** v6.2.0
- **NPM version:** 3.8.9
- **RethinkDB version:** rethinkdb 2.3.4 (CLANG 7.3.0 (clang-703.0.31))
- **Estimated effort:** 2 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
@mattkrick, I think we put the nail in this one when we were together, yes?

**Comment by mattkrick** [comment]
yep, this specific error (teamDash -> meeting) should be solved. We'll still see the "need a websocket" error anytime the server is restarted & a browser is still open.
