### ISSUE TITLE
Slack integration TypeError: Cannot read property 'viewerId' of undefined

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#2576]
https://sentry.io/parabol/action-production/issues/841465625/?referrer=github_plugin

```
TypeError: Cannot read property 'viewerId' of undefined
  at n.a (/production/build/v3.1.0/SlackIntegrationsRoot_3070ce3aac84e3a394d2.js:1:9942)
  at onClick (/production/build/v3.1.0/SlackIntegrationsRoot_3070ce3aac84e3a394d2.js:1:27373)
  at Object.<anonymous> (/production/build/v3.1.0/vendors~app_e9e71d8473d7be84a20f.js:98:880)
  at p (/production/build/v3.1.0/vendors~app_e9e71d8473d7be84a20f.js:98:918)
  at None (/production/build/v3.1.0/vendors~app_e9e71d8473d7be84a20f.js:98:1556)
...
(11 additional frame(s) were not displayed)
```

**Comment by jordanh** [comment]
Needs AC & EE, see also #1964

**Comment by mattkrick** [comment]
Sentry issue: [ACTION-PRODUCTION-GN](https://sentry.io/parabol/action-production/issues/823624756/?referrer=github_plugin)

**Comment by jordanh** [comment]
AC:
  - Triage to root cause (possible opening new issue), fix if less than EE

EE: 11 points
