### ISSUE TITLE
TypeError: this.atmosphere.getMasonry is not a function

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2605]
https://sentry.io/parabol/action-production/issues/861598806/?referrer=github_plugin

```
TypeError: this.atmosphere.getMasonry is not a function
  at Object.StartDraggingReflectionMutation (/production/build/v3.2.0/app_ad2d5eae1d7e93d264c9.js:1:44558)
  at Z.pendingBotAction (/production/build/v3.2.0/app_ad2d5eae1d7e93d264c9.js:1:38824)
  at pendingBotTimeout.window.setTimeout (/production/build/v3.2.0/app_ad2d5eae1d7e93d264c9.js:1:38939)
  at o (/production/build/v3.2.0/vendors~app_c31a495c491190447885.js:107:8764)
```

**Comment by mattkrick** [comment]
this happens in the demo during the group phase when they click the upper left logo that goes to /create-account

**Comment by jordanh** [comment]
AC:
  - Triage to root cause (possible opening new issue), fix if less than EE

EE: 11 points
