### ISSUE TITLE
TypeError: Cannot read property 'left' of undefined

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2606]
https://sentry.io/parabol/action-production/issues/858464882/?referrer=github_plugin

```
TypeError: Cannot read property 'left' of undefined
  at Da (/production/build/v3.2.0/RetroRoot_1daf09f5b5bda8fc2702.js:35:386147)
  at HTMLDocument.setViewerDragState.e (/production/build/v3.2.0/RetroRoot_1daf09f5b5bda8fc2702.js:35:388720)
  at HTMLDocument.o (/production/build/v3.2.0/vendors~app_c31a495c491190447885.js:107:8764)
```

**Comment by jordanh** [comment]
AC:
  - Triage to root cause (possible opening new issue), fix if less than EE

EE: 11 points

**Comment by mattkrick** [comment]
dupe #2610
