### ISSUE TITLE
TypeError: Cannot read property 'left' of undefined

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2610]
https://sentry.io/parabol/action-production/issues/839441061/?referrer=github_plugin

```
TypeError: Cannot read property 'left' of undefined
  at Da (/production/build/v3.1.0/RetroRoot_a3a996d8f7895cf1155a.js:35:383901)
  at HTMLDocument.setViewerDragState.e (/production/build/v3.1.0/RetroRoot_a3a996d8f7895cf1155a.js:35:386474)
  at HTMLDocument.o (/production/build/v3.1.0/vendors~app_e9e71d8473d7be84a20f.js:107:8764)
```

See handleDropOnGrid.js L25

**Comment by jordanh** [comment]
AC:
  - Triage to root cause (possible opening new issue), fix if less than EE

EE: 11 points
