### ISSUE TITLE
TypeError: Cannot read property 'viewerId' of undefined

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2611]
https://sentry.io/parabol/action-production/issues/823624576/?referrer=github_plugin

```
TypeError: Cannot read property 'viewerId' of undefined
  at n.a (/production/build/v3.0.0/SlackIntegrationsRoot~TeamIntegrationsRoot_bb71e4a1464aed16fdc7.js:1:12013)
  at i.a.createElement.i.a.createElement.onClick.e (/production/build/v3.0.0/SlackIntegrationsRoot_a250249ba1560d623927.js:1:27961)
  at Object.<anonymous> (/production/build/v3.0.0/vendors~app_7ba0f255af0b4dbcac94.js:98:880)
  at p (/production/build/v3.0.0/vendors~app_7ba0f255af0b4dbcac94.js:98:918)
  at None (/production/build/v3.0.0/vendors~app_7ba0f255af0b4dbcac94.js:98:1554)
...
(12 additional frame(s) were not displayed)
```

This occurs on a child of SlackIntegrations.tsx

**Comment by jordanh** [comment]
AC:
  - Triage to root cause (possible opening new issue), fix if less than EE

EE: 11 points
