### ISSUE TITLE
TypeError: Cannot read property 'agendaId' of undefined

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2612]
https://sentry.io/parabol/action-production/issues/844396540/?referrer=github_plugin

```
TypeError: Cannot read property 'agendaId' of undefined
  at Object.UpdateTaskMutation (/production/build/v3.1.0/app_7a79d86e1bbf82deed08.js:1:54580)
  at Z.pendingBotAction (/production/build/v3.1.0/app_7a79d86e1bbf82deed08.js:1:41019)
  at pendingBotTimeout.window.setTimeout (/production/build/v3.1.0/app_7a79d86e1bbf82deed08.js:1:41134)
  at o (/production/build/v3.1.0/vendors~app_e9e71d8473d7be84a20f.js:107:8764)
```

happens in demo

**Comment by jordanh** [comment]
AC:
  - Triage to root cause (possible opening new issue), fix if less than EE

EE: 11 points

**Comment by jordanh** [comment]
This one might have gotten fixed. Not sure!
