### ISSUE TITLE
Invariant Violation: Cannot call hover after drop.

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2652]
https://sentry.io/parabol/action-production/issues/895456301/?referrer=github_plugin

```
Invariant Violation: Cannot call hover after drop.
  at invariant (./node_modules/invariant/browser.js:38:1)
  at checkInvariants (./node_modules/dnd-core/lib/cjs/actions/dragDrop/hover.js:31:1)
  at apply (./node_modules/dnd-core/lib/cjs/actions/dragDrop/hover.js:12:1)
  at hover (./node_modules/dnd-core/lib/cjs/DragDropManagerImpl.js:58:1)
  at apply (./node_modules/react-dnd-html5-backend/lib/cjs/HTML5Backend.js:169:1)
...
(1 additional frame(s) were not displayed)
```

**Comment by mattkrick** [comment]
Sentry issue: [ACTION-PRODUCTION-P0](https://sentry.io/parabol/action-production/issues/895456300/?referrer=github_plugin)

**Comment by jordanh** [comment]
Might be fixed after grouping is refactored on `beautiful-grouping` branch. May reopen if not the case.
