### ISSUE TITLE
TypeError: Cannot read property 'newMeeting' of null

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2665]
https://sentry.io/parabol/action-production/issues/885076488/?referrer=github_plugin

```
TypeError: Cannot read property 'newMeeting' of null
  at updateRelayFromURL (./src/universal/components/NewMeetingWithLocalState.tsx:108:12)
  at new <anonymous> (./src/universal/components/NewMeetingWithLocalState.tsx:44:28)
  at onDataChange (./src/universal/components/QueryRenderer/QueryRenderer.js:195:12)
  at Array.forEach (<anonymous>)
...
(21 additional frame(s) were not displayed)
```

**Comment by mattkrick** [comment]
dupe of #2651
