### ISSUE TITLE
TypeError: Cannot read property 'viewerId' of undefined

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2694]
https://sentry.io/organizations/parabol/issues/895929131/?project=107196&referrer=github_plugin

```
TypeError: Cannot read property 'viewerId' of undefined
  at Object (./src/universal/mutations/RemoveSlackChannelMutation.js:25:10)
  at apply (./src/universal/modules/teamDashboard/components/SlackIntegrations/SlackIntegrations.tsx:83:5)
...
(11 additional frame(s) were not displayed)
```

Fix remove slack

**Comment by jordanh** [comment]
Closing, will reopen if resurfaces and/or we re-prioritize it
