### ISSUE TITLE
TypeError: null is not an object (evaluating 'this.el.scrollIntoView')

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2747]
https://sentry.io/organizations/parabol/issues/888648981/?project=107196&referrer=github_plugin

```
TypeError: null is not an object (evaluating 'this.el.scrollIntoView')
  at cb (./src/universal/modules/teamDashboard/components/AgendaItem/AgendaItem.js:82:14)
  at apply (./src/universal/utils/requestIdleCallback.js:5:5)
```

AC
- [ ] no error thrown in sentry

Effort: 11

no repro known

**Comment by jordanh** [comment]
Do we have reproduction criteria for this?

**Comment by mattkrick** [comment]
edited

**Comment by jordanh** [comment]
scrubbed, iceboxing for now
