### ISSUE TITLE
SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2748]
https://sentry.io/organizations/parabol/issues/891175973/?project=107196&referrer=github_plugin

```
SyntaxError: Unexpected token u in JSON at position 0
  at JSON.parse (<anonymous>)
  at c (./src/universal/components/ReflectionCard/ReflectionCard.tsx:67:46)
  at Set.forEach (<anonymous>)
  at run (./src/universal/LinearPublishQueue.ts:196:17)
...
(26 additional frame(s) were not displayed)
```

AC
- [ ] no error thrown in sentry

Effort: 11

no repro known

**Comment by jordanh** [comment]
Do we know what causes this?

**Comment by mattkrick** [comment]
edited

**Comment by jordanh** [comment]
Scrubbed. Iceboxing
