### ISSUE TITLE
TypeError: Cannot set property 'ontrack' of null

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2846]
https://sentry.io/organizations/parabol/issues/968397775/?project=107196&referrer=github_plugin

```
TypeError: Cannot set property 'ontrack' of null
  at Map.forEach (<anonymous>)
  at current (./src/universal/utils/swarm/MediaSwarm.ts:215:10)
  at d (./src/universal/hooks/useSwarm.tsx:37:40)
  at Array.forEach (<anonymous>)
  at handler (./src/universal/mutations/EndNewMeetingMutation.js:69:15)
...
(35 additional frame(s) were not displayed)
```

AC
- [ ] root cause triaged
Effort: 11

**Comment by mattkrick** [comment]
Sentry issue: [ACTION-PRODUCTION-10J](https://sentry.io/organizations/parabol/issues/969902041/?project=107196&referrer=github_plugin)

**Comment by jordanh** [comment]
Scrubbed. Added to project, added label and milestone.

**Comment by jordanh** [comment]
Scrubbed. Iceboxing.
