### ISSUE TITLE
TypeError: e.upgradeTransport is not a function. (In 'e.upgradeTransport()', 'e.upgradeTransport' is undefined)

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2848]
https://sentry.io/organizations/parabol/issues/971702827/?project=107196&referrer=github_plugin

```
TypeError: e.upgradeTransport is not a function. (In 'e.upgradeTransport()', 'e.upgradeTransport' is undefined)
  at None (./src/universal/components/DemoMeeting.tsx:17:21)
  at asyncFunctionResume ([native code])
  at e (./src/universal/components/DemoMeeting.tsx:17:21)
  at None ([native code])
  at handleDataChange (./src/universal/components/QueryRenderer/QueryRenderer.js:198:12)
...
(22 additional frame(s) were not displayed)
```

AC
- [ ] upgradeTransport not called from demo

Effort 10.5

**Comment by jordanh** [comment]
Scrubbed. Added to project, added label and milestone.

**Comment by mattkrick** [comment]
Needs repro on iOS mobile safari @jordanh

**Comment by jordanh** [comment]
Scrubbed. Iceboxing for now
