### ISSUE TITLE
TypeError: t[r.status] is undefined

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2852]
https://sentry.io/organizations/parabol/issues/1000287887/?project=107196&referrer=github_plugin

```
TypeError: t[r.status] is undefined
  at makeTasksByStatus (./src/universal/utils/makeTasksByStatus.js:13:5)
  at this (./src/universal/components/TaskColumns/TaskColumns.js:48:14)
  at e (./src/universal/components/TaskColumns/TaskColumns.js:34:5)
  at onDataChange (./src/universal/components/QueryRenderer/QueryRenderer.js:198:7)
...
(21 additional frame(s) were not displayed)
```

AC
- [ ] root cause triaged

Effort: 11 points

**Comment by jordanh** [comment]
Scrubbed. Added to project, added label and milestone.

**Comment by mattkrick** [comment]
haven't see it in 30 days, iceboxing
