### ISSUE TITLE
When no meeting agenda items, progress to last call

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#293]
## Issue - Bug

When on the meeting first call for agenda items, if the Facilitator simply advances the meeting with the "next" button, then skip to last call.

At present the meeting does not advance.

- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
You also see the following message on the console:

```
DEBUG GraphQL Error: [ { Error: {"_error":"We don't have that many agenda items!"}
      at errorObj (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/graphql/models/utils.js:5:32)
      at _callee2$ (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/graphql/models/Team/teamMutation.js:104:17)
      at tryCatch (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/regenerator-runtime/runtime.js:62:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/regenerator-runtime/runtime.js:336:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/regenerator-runtime/runtime.js:95:21)
      at step (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/graphql/models/Team/teamMutation.js:26:1)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/graphql/models/Team/teamMutation.js:26:1
      at run (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/core-js/modules/es6.promise.js:87:22)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/core-js/modules/es6.promise.js:100:28
      at flush (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/core-js/modules/_microtask.js:18:9)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
    message: '{"_error":"We don\'t have that many agenda items!"}',
    locations: [ [Object] ],
    path: [ 'moveMeeting' ] } ]
```
