### ISSUE TITLE
ReferenceError: Cannot access uninitialized variable.

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#2964]
https://sentry.io/organizations/parabol/issues/1057016771/?referrer=github_plugin

```
ReferenceError: Cannot access uninitialized variable.
  at e (./src/universal/modules/summary/components/NewMeetingSummary.tsx:27:43)
  at None ([native code])
  at handleDataChange (./src/universal/styles/theme/globalStyles.js:64:40)
  at forEach ([native code])
  at promiseReactionJob ([native code])
...
(20 additional frame(s) were not displayed)
```

AC
- [ ] redirect to /me

**Comment by mattkrick** [comment]
already fixed on master
