### ISSUE TITLE
TypeError: Cannot destructure property `isConnected` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#3197]
https://sentry.io/organizations/parabol/issues/1222971398/?referrer=github_plugin

```
TypeError: Cannot destructure property `isConnected` of 'undefined' or 'null'.
  at c (../client/components/DashboardAvatars/DashboardAvatar.tsx:53:18)
  at hg (/home/circleci/action/node_modules/react-dom/cjs/react-dom.production.min.js:150:94)
  at Tg (/home/circleci/action/node_modules/react-dom/cjs/react-dom.production.min.js:178:123)
  at bi (/home/circleci/action/node_modules/react-dom/cjs/react-dom.production.min.js:232:16)
  at ci (/home/circleci/action/node_modules/react-dom/cjs/react-dom.production.min.js:233:281)
...
(5 additional frame(s) were not displayed)
```

AC
- [ ] find null user

effort: 10.5

**Comment by mattkrick** [comment]
Sentry issue: [ACTION-PRODUCTION-23B](https://sentry.io/organizations/parabol/issues/1234541493/?referrer=github_plugin)

**Comment by mattkrick** [comment]
this is a very strange one. user is guaranteed nonnull from the server. there's no exception on the server.

**Comment by mattkrick** [comment]
added extra logging & a graceful error handler
