### ISSUE TITLE
Error during meeting crashes browser

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/action#346]
It seems to happen when navigating to First and/or Last Call views during a Meeting. Perhaps it has something to do with Agenda Items? I’m also wondering if it happens when pressing `enter` opposed to just clicking the “Next” link. Hard to reproduce consistently.

The console message:

```Creating a pool connected to localhost:28015
DEBUG GraphQL Subscribe Error: [ { GraphQLError: Variable "$teamMemberId" of required type "ID!" was not provided.
      at getVariableValue (/Users/terryacker/code/parabolinc/action/node_modules/graphql/execution/values.js:107:11)
      at /Users/terryacker/code/parabolinc/action/node_modules/graphql/execution/values.js:55:23
      at Array.reduce (native)
      at getVariableValues (/Users/terryacker/code/parabolinc/action/node_modules/graphql/execution/values.js:53:25)
      at buildExecutionContext (/Users/terryacker/code/parabolinc/action/node_modules/graphql/execution/execute.js:158:54)
      at execute (/Users/terryacker/code/parabolinc/action/node_modules/graphql/execution/execute.js:99:17)
      at Promise.catch.error.errors (/Users/terryacker/code/parabolinc/action/node_modules/graphql/graphql.js:58:36)
      at graphql (/Users/terryacker/code/parabolinc/action/node_modules/graphql/graphql.js:51:10)
      at Emitter._callee$ (/Users/terryacker/code/parabolinc/action/src/server/socketHandlers/scSubscribeHandler.js:51:28)
      at tryCatch (/Users/terryacker/code/parabolinc/action/node_modules/regenerator-runtime/runtime.js:62:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/terryacker/code/parabolinc/action/node_modules/regenerator-runtime/runtime.js:336:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/terryacker/code/parabolinc/action/node_modules/regenerator-runtime/runtime.js:95:21)
      at step (/Users/terryacker/code/parabolinc/action/src/server/socketHandlers/scSubscribeHandler.js:5:1)
      at /Users/terryacker/code/parabolinc/action/src/server/socketHandlers/scSubscribeHandler.js:5:1
      at Emitter.<anonymous> (/Users/terryacker/code/parabolinc/action/src/server/socketHandlers/scSubscribeHandler.js:5:1)
      at Emitter.subscribeHandler (/Users/terryacker/code/parabolinc/action/src/server/socketHandlers/scSubscribeHandler.js:35:3)
      at Emitter.emit (/Users/terryacker/code/parabolinc/action/node_modules/sc-emitter/node_modules/component-emitter/index.js:131:20)
      at Emitter.SCEmitter.emit (/Users/terryacker/code/parabolinc/action/node_modules/sc-emitter/index.js:28:26)
      at Emitter.SCSocket.emit (/Users/terryacker/code/parabolinc/action/node_modules/socketcluster-server/scsocket.js:283:30)
      at /Users/terryacker/code/parabolinc/action/node_modules/socketcluster-server/scserver.js:218:16
      at addSubscription (/Users/terryacker/code/parabolinc/action/node_modules/sc-broker-cluster/index.js:612:17)
      at callback (/Users/terryacker/code/parabolinc/action/node_modules/sc-broker/index.js:304:26)
    message: 'Variable "$teamMemberId" of required type "ID!" was not provided.',
    locations: [ [Object] ],
    path: undefined } ]
Client disconnected: K2oq6xlEnAmQgzREAAAA
DEBUG GraphQL Subscribe Error: [ { GraphQLError: Variable "$teamMemberId" of required type "ID!" was not provided.
      at getVariableValue (/Users/terryacker/code/parabolinc/action/node_modules/graphql/execution/values.js:107:11)
      at /Users/terryacker/code/parabolinc/action/node_modules/graphql/execution/values.js:55:23
      at Array.reduce (native)
      at getVariableValues (/Users/terryacker/code/parabolinc/action/node_modules/graphql/execution/values.js:53:25)
      at buildExecutionContext (/Users/terryacker/code/parabolinc/action/node_modules/graphql/execution/execute.js:158:54)
      at execute (/Users/terryacker/code/parabolinc/action/node_modules/graphql/execution/execute.js:99:17)
      at Promise.catch.error.errors (/Users/terryacker/code/parabolinc/action/node_modules/graphql/graphql.js:58:36)
      at graphql (/Users/terryacker/code/parabolinc/action/node_modules/graphql/graphql.js:51:10)
      at Emitter._callee$ (/Users/terryacker/code/parabolinc/action/src/server/socketHandlers/scSubscribeHandler.js:51:28)
      at tryCatch (/Users/terryacker/code/parabolinc/action/node_modules/regenerator-runtime/runtime.js:62:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/terryacker/code/parabolinc/action/node_modules/regenerator-runtime/runtime.js:336:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/terryacker/code/parabolinc/action/node_modules/regenerator-runtime/runtime.js:95:21)
      at step (/Users/terryacker/code/parabolinc/action/src/server/socketHandlers/scSubscribeHandler.js:5:1)
      at /Users/terryacker/code/parabolinc/action/src/server/socketHandlers/scSubscribeHandler.js:5:1
      at Emitter.<anonymous> (/Users/terryacker/code/parabolinc/action/src/server/socketHandlers/scSubscribeHandler.js:5:1)
      at Emitter.subscribeHandler (/Users/terryacker/code/parabolinc/action/src/server/socketHandlers/scSubscribeHandler.js:35:3)
      at Emitter.emit (/Users/terryacker/code/parabolinc/action/node_modules/sc-emitter/node_modules/component-emitter/index.js:131:20)
      at Emitter.SCEmitter.emit (/Users/terryacker/code/parabolinc/action/node_modules/sc-emitter/index.js:28:26)
      at Emitter.SCSocket.emit (/Users/terryacker/code/parabolinc/action/node_modules/socketcluster-server/scsocket.js:283:30)
      at /Users/terryacker/code/parabolinc/action/node_modules/socketcluster-server/scserver.js:218:16
      at addSubscription (/Users/terryacker/code/parabolinc/action/node_modules/sc-broker-cluster/index.js:612:17)
      at callback (/Users/terryacker/code/parabolinc/action/node_modules/sc-broker/index.js:304:26)
    message: 'Variable "$teamMemberId" of required type "ID!" was not provided.',
    locations: [ [Object] ],
    path: undefined } ]```

**Comment by mattkrick** [comment]
Oh man, so many good bugs!
So I can reproduce this by going to lastCall & then clicking updates on the sidebar.

So, this is caused because localPhaseItem it required to grab the teamMemberId.
localPhaseItem is undefined because something is triggering a re-render while still on the lastcall phase.
So there are a few things we should do: 
1. code defensively, if a component isn't going to receive the props that it should, we need to just not load that component, we know it'll get loaded correctly on the next tick.
2. figure out what is causing it to load a 2nd time. it may just be some redux dispatch that gets dispatched prior to the route getting changed. regardless, it's extraneous CPU cycles.
