### ISSUE TITLE
Server crashing on localhost

### ISSUE THREAD

**Issue by monarkmodi** [ParabolInc/action#433]
## Issue
The server crashes on opening the webpage for Action on http://localhost:3000. Able to start the server with `npm run quickstart` and `rethinkdb` (In new tab). But the request does not go through and breaks the server. Here is the issue: 

```
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/Cellar/node/5.7.1/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! parabol-action@0.8.1 build: `rimraf build && concurrently "npm run build:client" "npm run build:server"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the parabol-action@0.8.1 build script 'rimraf build && concurrently "npm run build:client" "npm run build:server"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the parabol-action package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rimraf build && concurrently "npm run build:client" "npm run build:server"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs parabol-action
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls parabol-action
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tathastu/Desktop/Parabol/action/npm-debug.log

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/Cellar/node/5.7.1/bin/node" "/usr/local/bin/npm" "run" "quickstart"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! parabol-action@0.8.1 quickstart: `npm run db:migrate && npm run build && npm run start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the parabol-action@0.8.1 quickstart script 'npm run db:migrate && npm run build && npm run start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the parabol-action package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run db:migrate && npm run build && npm run start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs parabol-action
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls parabol-action
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tathastu/Desktop/Parabol/action/npm-debug.log
```

**Browser**: Google Chrome Version 53.0.2785.143
**OS**: MacOS Sierra 10.12
**Node**: 5.7.1
**Rethinkdb**: 2.3.5

**Comment by mattkrick** [comment]
@monarkmodi go ahead & upgrade to the latest version of node. I recommend using `n`. (`sudo npm i -g n && n latest`)

**Comment by monarkmodi** [comment]
No luck!

**Comment by mattkrick** [comment]
what does your error log look like?

**Comment by monarkmodi** [comment]
```
> parabol-action@0.9.3 quickstart /Users/tathastu/Desktop/Parabol/action
> npm run db:migrate && npm run build && npm run start


> parabol-action@0.9.3 db:migrate /Users/tathastu/Desktop/Parabol/action
> ./src/server/database/migrate.sh up-all

will migrate up all
[rethink-migrate] Connecting to database
Creating a pool connected to localhost:28015
[rethink-migrate] Connected
[rethink-migrate] No new migrations
[rethink-migrate] Migration successful

> parabol-action@0.9.3 build /Users/tathastu/Desktop/Parabol/action
> rimraf build && concurrently "npm run build:client" "npm run build:server"

[0] 
[0] > parabol-action@0.9.3 build:client /Users/tathastu/Desktop/Parabol/action
[0] > NODE_ENV=production webpack --config ./webpack/prod.babel.js
[0] 
[1] 
[1] > parabol-action@0.9.3 build:server /Users/tathastu/Desktop/Parabol/action
[1] > NODE_ENV=production webpack --config ./webpack/server.babel.js
[1] 
[1] Executing pre-build scripts
[0] Executing pre-build scripts
[1] acquired ./build/appTheme.json.lock, creating ./build/appTheme.json...
[1] released ./build/appTheme.json.lock.
[0] waiting on ./build/appTheme.json.lock...
[0] acquired ./build/appTheme.json.lock, creating ./build/appTheme.json...
[0] released ./build/appTheme.json.lock.
[1] Hash: ad2cb099f97edc7b5f5d
[1] Version: webpack 2.1.0-beta.22
[1] Time: 39373ms
[1]     + 1207 hidden modules
[1] 
[1] ERROR in ../~/cashay/lib/schema/cashay-loader.js!./server/utils/getCashaySchema.js
[1] Module build failed: Error: Module version mismatch. Expected 48, got 47.
[1]     at Error (native)
[1]     at Object.Module._extensions..node (module.js:597:18)
[1]     at Module.load (module.js:487:32)
[1]     at tryModuleLoad (module.js:446:12)
[1]     at Function.Module._load (module.js:438:3)
[1]     at Module.require (module.js:497:17)
[1]     at require (internal/module.js:20:19)
[1]     at bindings (/Users/tathastu/Desktop/Parabol/action/node_modules/bindings/bindings.js:76:44)
[1]     at Object.<anonymous> (/Users/tathastu/Desktop/Parabol/action/node_modules/bcrypt/bcrypt.js:3:35)
[1]     at Module._compile (module.js:570:32)
[1]     at Module._extensions..js (module.js:579:10)
[1]     at Object.require.extensions.(anonymous function) [as .js] (/Users/tathastu/Desktop/Parabol/action/node_modules/babel-register/lib/node.js:154:7)
[1]     at Module.load (module.js:487:32)
[1]     at tryModuleLoad (module.js:446:12)
[1]     at Function.Module._load (module.js:438:3)
[1]     at Module.require (module.js:497:17)
[1]     at require (internal/module.js:20:19)
[1]     at Object.<anonymous> (/Users/tathastu/Desktop/Parabol/action/src/server/graphql/models/Invitation/helpers.js:5:1)
[1]     at Module._compile (module.js:570:32)
[1]     at loader (/Users/tathastu/Desktop/Parabol/action/node_modules/babel-register/lib/node.js:146:5)
[1]     at Object.require.extensions.(anonymous function) [as .js] (/Users/tathastu/Desktop/Parabol/action/node_modules/babel-register/lib/node.js:156:7)
[1]     at Module.load (module.js:487:32)
[1]     at tryModuleLoad (module.js:446:12)
[1]     at Function.Module._load (module.js:438:3)
[1]     at Module.require (module.js:497:17)
[1]     at require (internal/module.js:20:19)
[1]     at Object.<anonymous> (/Users/tathastu/Desktop/Parabol/action/src/server/graphql/models/Invitation/invitationMutation.js:10:1)
[1]     at Module._compile (module.js:570:32)
[1]     at loader (/Users/tathastu/Desktop/Parabol/action/node_modules/babel-register/lib/node.js:146:5)
[1]     at Object.require.extensions.(anonymous function) [as .js] (/Users/tathastu/Desktop/Parabol/action/node_modules/babel-register/lib/node.js:156:7)
[1]     at Module.load (module.js:487:32)
[1]     at tryModuleLoad (module.js:446:12)
[1]     at Function.Module._load (module.js:438:3)
[1]     at Module.require (module.js:497:17)
[1]     at require (internal/module.js:20:19)
[1]     at Object.<anonymous> (/Users/tathastu/Desktop/Parabol/action/src/server/graphql/rootMutation.js:4:1)
[1]  @ ./universal/routes/index.js 30:23-72
[1] 
[1] npm
[1]  ERR! Darwin 16.0.0
[1] npm ERR! argv
[1]  "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:server"
[1] npm ERR! 
[1] node v6.9.1
[1] npm
[1]  ERR! npm  v3.10.8
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! parabol-action@0.9.3 build:server: `NODE_ENV=production webpack --config ./webpack/server.babel.js`
[1] npm ERR! Exit status 2
[1] npm ERR! 
[1] npm ERR! Failed at the parabol-action@0.9.3 build:server script 'NODE_ENV=production webpack --config ./webpack/server.babel.js'.
[1] npm ERR! Make sure you have the latest version of node.js and npm installed.
[1] npm ERR! If you do, this is most likely a problem with the parabol-action package,
[1] npm ERR! not with npm itself.
[1] npm ERR! Tell the author that this fails on your system:
[1] npm ERR!     NODE_ENV=production webpack --config ./webpack/server.babel.js
[1] npm ERR! You can get information on how to open an issue for this project with:
[1] npm ERR!     npm bugs parabol-action
[1] npm 
[1] ERR! Or if that isn't available, you can get their info via:
[1] npm ERR!     npm owner ls parabol-action
[1] npm ERR! There is likely additional logging output above.
[1] 
[1] npm ERR!
[1]  Please include the following file with any support request:
[1] npm ERR!     /Users/tathastu/Desktop/Parabol/action/npm-debug.log
[1] npm run build:server exited with code 1
[0] Hash: 3c8cb58d2fcae3fbaba8
[0] Version: webpack 2.1.0-beta.22
[0] Time: 41500ms
[0]    [0] multi app 40 bytes {8} [built]
[0]    [1] multi vendor 100 bytes {9} [built]
[0]     + 1533 hidden modules
[0] 
[0] WARNING in AUTH0_CLIENT_ID environment variable is undefined.
[0] 
[0] WARNING in AUTH0_DOMAIN environment variable is undefined.
[0] 
[0] WARNING in HOST environment variable is undefined.
[0] 
[0] WARNING in PORT environment variable is undefined.
[0] 
[0] ERROR in ../~/cashay/lib/schema/cashay-loader.js!./server/utils/getCashaySchema.js
[0] Module build failed: Error: Module version mismatch. Expected 48, got 47.
[0]     at Error (native)
[0]     at Object.Module._extensions..node (module.js:597:18)
[0]     at Module.load (module.js:487:32)
[0]     at tryModuleLoad (module.js:446:12)
[0]     at Function.Module._load (module.js:438:3)
[0]     at Module.require (module.js:497:17)
[0]     at require (internal/module.js:20:19)
[0]     at bindings (/Users/tathastu/Desktop/Parabol/action/node_modules/bindings/bindings.js:76:44)
[0]     at Object.<anonymous> (/Users/tathastu/Desktop/Parabol/action/node_modules/bcrypt/bcrypt.js:3:35)
[0]     at Module._compile (module.js:570:32)
[0]     at Module._extensions..js (module.js:579:10)
[0]     at Object.require.extensions.(anonymous function) [as .js] (/Users/tathastu/Desktop/Parabol/action/node_modules/babel-register/lib/node.js:154:7)
[0]     at Module.load (module.js:487:32)
[0]     at tryModuleLoad (module.js:446:12)
[0]     at Function.Module._load (module.js:438:3)
[0]     at Module.require (module.js:497:17)
[0]     at require (internal/module.js:20:19)
[0]     at Object.<anonymous> (/Users/tathastu/Desktop/Parabol/action/src/server/graphql/models/Invitation/helpers.js:5:1)
[0]     at Module._compile (module.js:570:32)
[0]     at loader (/Users/tathastu/Desktop/Parabol/action/node_modules/babel-register/lib/node.js:146:5)
[0]     at Object.require.extensions.(anonymous function) [as .js] (/Users/tathastu/Desktop/Parabol/action/node_modules/babel-register/lib/node.js:156:7)
[0]     at Module.load (module.js:487:32)
[0]     at tryModuleLoad (module.js:446:12)
[0]     at Function.Module._load (module.js:438:3)
[0]     at Module.require (module.js:497:17)
[0]     at require (internal/module.js:20:19)
[0]     at Object.<anonymous> (/Users/tathastu/Desktop/Parabol/action/src/server/graphql/models/Invitation/invitationMutation.js:10:1)
[0]     at Module._compile (module.js:570:32)
[0]     at loader (/Users/tathastu/Desktop/Parabol/action/node_modules/babel-register/lib/node.js:146:5)
[0]     at Object.require.extensions.(anonymous function) [as .js] (/Users/tathastu/Desktop/Parabol/action/node_modules/babel-register/lib/node.js:156:7)
[0]     at Module.load (module.js:487:32)
[0]     at tryModuleLoad (module.js:446:12)
[0]     at Function.Module._load (module.js:438:3)
[0]     at Module.require (module.js:497:17)
[0]     at require (internal/module.js:20:19)
[0]     at Object.<anonymous> (/Users/tathastu/Desktop/Parabol/action/src/server/graphql/rootMutation.js:4:1)
[0]  @ ./client/client.js 25:23-75
[0]  @ multi app
[0] 
[0] npm
[0]  ERR! Darwin 16.0.0
[0] npm ERR!
[0]  
[0] argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:client"
[0] npm ERR! node v6.9.1
[0] npm ERR! npm  v3.10.8
[0] npm ERR! code ELIFECYCLE
[0] npm ERR! parabol-action@0.9.3 build:client: `NODE_ENV=production webpack --config ./webpack/prod.babel.js`
[0] npm ERR! Exit status 2
[0] npm ERR! 
[0] npm ERR! Failed at the parabol-action@0.9.3 build:client script 'NODE_ENV=production webpack --config ./webpack/prod.babel.js'.
[0] npm ERR! Make sure you have the latest version of node.js and npm installed.
[0] npm ERR!
[0]  If you do, this is most likely a problem with the parabol-action package,
[0] npm ERR! not with npm itself.
[0] npm ERR! Tell the author that this fails on your system:
[0] npm ERR!     NODE_ENV=production webpack --config ./webpack/prod.babel.js
[0] npm ERR!
[0]  You can get information on how to open an issue for this project with:
[0] npm ERR!     npm bugs parabol-action
[0] npm ERR! Or if that isn't available, you can get their info via:
[0] npm ERR!     npm owner ls parabol-action
[0] npm ERR! There is likely additional logging output above.
[0] 
[0] npm ERR! Please include the following file with any support request:
[0] npm 
[0] ERR!     /Users/tathastu/Desktop/Parabol/action/npm-debug.log
[0] npm run build:client exited with code 1

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! parabol-action@0.9.3 build: `rimraf build && concurrently "npm run build:client" "npm run build:server"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the parabol-action@0.9.3 build script 'rimraf build && concurrently "npm run build:client" "npm run build:server"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the parabol-action package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rimraf build && concurrently "npm run build:client" "npm run build:server"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs parabol-action
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls parabol-action
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tathastu/Desktop/Parabol/action/npm-debug.log

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "quickstart"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! parabol-action@0.9.3 quickstart: `npm run db:migrate && npm run build && npm run start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the parabol-action@0.9.3 quickstart script 'npm run db:migrate && npm run build && npm run start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the parabol-action package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run db:migrate && npm run build && npm run start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs parabol-action
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls parabol-action
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tathastu/Desktop/Parabol/action/npm-debug.log
```

**Comment by mattkrick** [comment]
alrighty, fixed the dependency mismatch. good to go!

**Comment by monarkmodi** [comment]
Pulled the changes and installed dep again but still same error.

**Comment by mattkrick** [comment]
go ahead and rm -rf node_modules & then `sudo npm i -g yarn && yarn add`. Yarn will use our shared lockfile so you're guaranteed to get the same stuff as us.

**Comment by monarkmodi** [comment]
Great! Got it up and running. :)
