### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#438]
https://sentry.io/parabol/action-production/issues/173835794/

```
TypeError: Cannot read property 'id' of undefined
  at checkCanDelete (/static/app_99426fdb3a734ccd8de2.js:6994:18)
  at processSubscriptionDoc (/static/app_99426fdb3a734ccd8de2.js:7024:23)
  at mergeNewData (/static/app_99426fdb3a734ccd8de2.js:3072:65)
  at remove (/static/app_99426fdb3a734ccd8de2.js:3190:11)
  at SCEmitter.<anonymous> (/static/0_21e74a6f329f56f1ec42.js:8555:7)
...
(9 additional frame(s) were not displayed)
```

**Comment by mattkrick** [comment]
fixed in the latest version of cashay.
