### ISSUE TITLE
Team settings sprint: alreadyTeamMember.join is not a function on re-add

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#510]
## Issue - Bug

When I invite a user by email 'frank@prbl.co', remove that user, then re-invite `frank@prbl.co` I receive an exception on the server console:

```javascript
DEBUG GraphQL Error: [ { TypeError: alreadyTeamMember.join is not a function
      at _callee$ (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/graphql/models/Invitation/invitationMutation.js:61:40)
      at tryCatch (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/regenerator-runtime/runtime.js:62:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/regenerator-runtime/runtime.js:336:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/regenerator-runtime/runtime.js:95:21)
      at step (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/graphql/models/Invitation/invitationMutation.js:12:1)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/graphql/models/Invitation/invitationMutation.js:12:1
      at run (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/core-js/modules/es6.promise.js:87:22)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/core-js/modules/es6.promise.js:100:28
      at flush (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/core-js/modules/_microtask.js:18:9)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)
    message: 'alreadyTeamMember.join is not a function',
    locations: [ [Object] ],
    path: [ 'inviteTeamMembers' ] } ]
```

- **OS:** OSX
- **Browser:** Chrome
- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
this requires extra thought. currently, we don't actually remove a team member, we set them to inactive.

- should we change copy to read active/inactive?
- should we show inactive team members? if not, should we do async validation to see if they're already on the team?
- should we treat it like we deleted the person? If so, then an invite token will simply serve to turn inactive to active.

**Comment by jordanh** [comment]
What do you think about making removal a two-step process: active->inactive->remove. Inactive members are shown in the list, so we won't need to need to do any asynchronous queries.

When a user is marked as inactive nothing changes w.r.t. their projects. When they are actually removed we delete their TeamMember object and reassign their projects to their team leader.

**Comment by mattkrick** [comment]
personally, i don't like deleting anything. Also, you mentioned that you want to hold onto archived items forever. if we remove a team member, that gets difficult.

perhaps we can write some user stories on when someone would inactive/remove a team member? i probably don't understand the use case.

**Comment by ackernaut** [comment]
What if both inactive and deleted team members were preserved in the data?

I’m not sure what an inactive team member can do? I’m assuming they cannot see the team dashboard and projects/actions for that team do not show up on their user dashboard? Team members can see the projects of the inactive team member? But they can still change them and reassign them?

I think a deleted team member would persist in history and in the data, but would not show up on the team member list, and all of their projects would have to be assigned. I think their actions would be marked as completed just to take them out of the user dashboard view.

I agree with @mattkrick on thinking of at least 1 or 2 basic user stories.

**Comment by ackernaut** [comment]
PS.

An inactive team member has to be reactivated by a team member and all is the same (if no projects were reassigned). They lose their actions if we marked them completed?

A deleted team member has to be re-invited to the team. The history of that person never changed, but they would not have any old projects as they were re-assigned. Do archived projects get re-assigned?

**Comment by mattkrick** [comment]
OK, so after a chat with @ackernaut here's the takeaways:
- auto-complete items when someone gets removed
- if the person invited is an inactive team member, we reactivate their account & pop a toast telling them that they were reactivated instead of invited
