### ISSUE TITLE
Team settings sprint: invitation server exception

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#515]
## Issue - Bug

While inviting a user from the new team settings controls, I see the following exception on the server:

```
      at Connection._processResponse (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/rethinkdbdash/lib/connection.js:382:15)
      at Socket.<anonymous> (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/rethinkdbdash/lib/connection.js:201:14)
      at emitOne (events.js:96:13)
      at Socket.emit (events.js:188:7)
      at Socket.EventEmitter.emit (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/sc-domain/index.js:12:31)
      at readableAddChunk (_stream_readable.js:177:18)
      at Socket.Readable.push (_stream_readable.js:135:10)
      at TCP.onread (net.js:542:20)
  From previous event:
      at Term.run (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/rethinkdbdash/lib/term.js:142:15)
      at Term.then (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/rethinkdbdash/lib/term.js:2876:15)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/core-js/modules/es6.promise.js:168:16
      at flush (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/core-js/modules/_microtask.js:18:9)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)
    message: 'Expected type DATUM but found SELECTION:\nSELECTION ON table(TeamMember) in:\nr.table("Invitation").getAll(r.args(["terry@prbl.co"]), {\n    index: "email"\n}).filter(r.row("tokenExpiration").ge(r.epochTime(1479213146277)))("email").coerceTo("array").do(function(var_91) {\n    return {\n        invites: var_91,\n        teamMembers: r.table("TeamMember").getAll("team456", {\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n            index: "teamId"\n            ^^^^^^^^^^^^^^^\n        })\n        ^^\n    }\n})\n',
    locations: [ [Object] ],
    path: [ 'inviteTeamMembers' ] } ]
DEBUG GraphQL Error: [ { ReqlLogicError: Expected type DATUM but found SELECTION:
  SELECTION ON table(TeamMember) in:
  r.table("Invitation").getAll(r.args(["terry@prbl.co"]), {
      index: "email"
  }).filter(r.row("tokenExpiration").ge(r.epochTime(1479213180570)))("email").coerceTo("array").do(function(var_93) {
      return {
          invites: var_93,
          teamMembers: r.table("TeamMember").getAll("team456", {
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              index: "teamId"
              ^^^^^^^^^^^^^^^
          })
          ^^
      }
  })
```

Note: this happens for `terry@prbl.co` or a new new user `foo@prbl.co`.

- **OS:** OSX
- **Browser:** Chrome
- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
whooops! the coercion got removed
