### ISSUE TITLE
Server exception encountered when generating meeting summary

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#517]
## Issue - Bug

Here's the stack trace:

```
2016-11-15T15:27:26.859661756Z app[web.1]:     message: 'Cannot return null for non-nullable field MeetingAction.content.',
2016-11-15T15:27:26.859666247Z app[web.1]:     locations: [ [Object] ],
2016-11-15T15:27:26.859670499Z app[web.1]:     path: [ 'summarizeMeeting', 'invitees', 0, 'actions', 3, 'content' ] },
2016-11-15T15:27:26.859674909Z app[web.1]:   { Error: Cannot return null for non-nullable field MeetingAction.content.
2016-11-15T15:27:26.859679276Z app[web.1]:       at completeValue (/app/node_modules/graphql/execution/execute.js:542:13)
2016-11-15T15:27:26.859683632Z app[web.1]:       at completeValueWithLocatedError (/app/node_modules/graphql/execution/execute.js:491:21)
2016-11-15T15:27:26.859688027Z app[web.1]:       at completeValueCatchingError (/app/node_modules/graphql/execution/execute.js:461:12)
2016-11-15T15:27:26.859692346Z app[web.1]:       at resolveField (/app/node_modules/graphql/execution/execute.js:440:10)
2016-11-15T15:27:26.859696762Z app[web.1]:       at /app/node_modules/graphql/execution/execute.js:245:18
2016-11-15T15:27:26.859700982Z app[web.1]:       at Array.reduce (native)
2016-11-15T15:27:26.859705154Z app[web.1]:       at executeFields (/app/node_modules/graphql/execution/execute.js:242:42)
2016-11-15T15:27:26.859709439Z app[web.1]:       at completeObjectValue (/app/node_modules/graphql/execution/execute.js:657:10)
2016-11-15T15:27:26.859715386Z app[web.1]:       at completeValue (/app/node_modules/graphql/execution/execute.js:571:12)
2016-11-15T15:27:26.859719759Z app[web.1]:       at completeValueWithLocatedError (/app/node_modules/graphql/execution/execute.js:491:21)
2016-11-15T15:27:26.859725346Z app[web.1]:       at completeValueCatchingError (/app/node_modules/graphql/execution/execute.js:467:21)
2016-11-15T15:27:26.859729872Z app[web.1]:       at /app/node_modules/graphql/execution/execute.js:594:25
2016-11-15T15:27:26.859738326Z app[web.1]:       at Array.forEach (native)
2016-11-15T15:27:26.859762729Z app[web.1]:       at forEach (/app/node_modules/iterall/index.js:272:25)
2016-11-15T15:27:26.859768641Z app[web.1]:       at completeListValue (/app/node_modules/graphql/execution/execute.js:590:24)
2016-11-15T15:27:26.859773036Z app[web.1]:       at completeValue (/app/node_modules/graphql/execution/execute.js:554:12)
2016-11-15T15:27:26.859777391Z app[web.1]:       at completeValueWithLocatedError (/app/node_modules/graphql/execution/execute.js:491:21)
2016-11-15T15:27:26.859781732Z app[web.1]:       at completeValueCatchingError (/app/node_modules/graphql/execution/execute.js:467:21)
2016-11-15T15:27:26.859785966Z app[web.1]:       at resolveField (/app/node_modules/graphql/execution/execute.js:440:10)
2016-11-15T15:27:26.859790201Z app[web.1]:       at /app/node_modules/graphql/execution/execute.js:245:18
2016-11-15T15:27:26.859794407Z app[web.1]:       at Array.reduce (native)
2016-11-15T15:27:26.859798491Z app[web.1]:       at executeFields (/app/node_modules/graphql/execution/execute.js:242:42)
2016-11-15T15:27:26.859820197Z app[web.1]:       at completeObjectValue (/app/node_modules/graphql/execution/execute.js:657:10)
2016-11-15T15:27:26.859826101Z app[web.1]:       at completeValue (/app/node_modules/graphql/execution/execute.js:571:12)
2016-11-15T15:27:26.859830634Z app[web.1]:       at completeValueWithLocatedError (/app/node_modules/graphql/execution/execute.js:491:21)
2016-11-15T15:27:26.859835111Z app[web.1]:       at completeValueCatchingError (/app/node_modules/graphql/execution/execute.js:467:21)
2016-11-15T15:27:26.859839621Z app[web.1]:       at /app/node_modules/graphql/execution/execute.js:594:25
2016-11-15T15:27:26.859844161Z app[web.1]:       at Array.forEach (native)
2016-11-15T15:27:26.859848481Z app[web.1]:       at forEach (/app/node_modules/iterall/index.js:272:25)
2016-11-15T15:27:26.859852876Z app[web.1]:       at completeListValue (/app/node_modules/graphql/execution/execute.js:590:24)
2016-11-15T15:27:26.859857525Z app[web.1]:       at completeValue (/app/node_modules/graphql/execution/execute.js:554:12)
2016-11-15T15:27:26.859861879Z app[web.1]:       at completeValueWithLocatedError (/app/node_modules/graphql/execution/execute.js:491:21)
2016-11-15T15:27:26.859866371Z app[web.1]:       at completeValueCatchingError (/app/node_modules/graphql/execution/execute.js:467:21)
2016-11-15T15:27:26.859870987Z app[web.1]:       at resolveField (/app/node_modules/graphql/execution/execute.js:440:10)
2016-11-15T15:27:26.859875237Z app[web.1]:       at /app/node_modules/graphql/execution/execute.js:245:18
2016-11-15T15:27:26.859900008Z app[web.1]:       at Array.reduce (native)
2016-11-15T15:27:26.859907718Z app[web.1]:       at executeFields (/app/node_modules/graphql/execution/execute.js:242:42)
2016-11-15T15:27:26.859912366Z app[web.1]:       at completeObjectValue (/app/node_modules/graphql/execution/execute.js:657:10)
2016-11-15T15:27:26.859916568Z app[web.1]:       at completeValue (/app/node_modules/graphql/execution/execute.js:571:12)
2016-11-15T15:27:26.859920811Z app[web.1]:       at /app/node_modules/graphql/execution/execute.js:528:14
2016-11-15T15:27:26.859925034Z app[web.1]:       at run (/app/node_modules/core-js/modules/es6.promise.js:87:22)
2016-11-15T15:27:26.859941151Z app[web.1]:       at /app/node_modules/core-js/modules/es6.promise.js:100:28
2016-11-15T15:27:26.859946488Z app[web.1]:       at flush (/app/node_modules/core-js/modules/_microtask.js:18:9)
2016-11-15T15:27:26.859950743Z app[web.1]:       at _combinedTickCallback (internal/process/next_tick.js:67:7)
2016-11-15T15:27:26.859954911Z app[web.1]:       at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

- **Estimated effort:** 1 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
this is caused when a project or action is created & does not have any content. ideally, this should never happen. in the off chance that it does, we should go through the new outcomes & delete the ones without content.
