### ISSUE TITLE
Howto get started with action as a boilerplate?

### ISSUE THREAD

**Issue by alvestjo** [ParabolInc/action#658]
Hi,

I am looking at using your project as a boilerplate instead of Meatier. It looks awsome! But I am having problems to get started.

I have cloned the repo and got it building and running. When I click the GET STARTED button on the frontpage I get the Auth0 authentication box and are able to sign-up and authenticate. However after login I get back to the start page and when I click the GET STARTED button again I get a new loginbox. I am not bale to do anything exept autenticting. Any Ideas? 

Do I need to setup Auth0 with my own CleintID etc? In that case should this be done in .env file?

Many thanks for a little getting started help!

//Jonas

**Comment by jordanh** [comment]
Hi @alvestjo!

Eventually, you'll want to create your own auth0 account but for starters you can get started with the default development credentials included in the code base.

Do you have an instance of rethinkdb running? Have you run the database migrations?

**Comment by alvestjo** [comment]
Thanks for your answer.

I have been working on this and it might be something wrong in my setup.
When I run npm run build i get this error:
`ERROR in ../~/cashay/lib/schema/cashay-loader.js!./server/utils/getCashaySchema.js
Module build failed: Error: C:/action-production/src/server/graphql/models/Meeting/meetingMutation.js: Cannot find module 'graphql' from 'C:\action-production\src\server\graphql\models\Meeting'
    at Function.module.exports [as sync] (C:\action-production\node_modules\resolve\lib\sync.js:36:11)
    at resolveModuleSource (C:\action-production\src\server\utils\getCashaySchema.js:15:20)
    at File.resolveModuleSource (C:\action-production\node_modules\babel-core\lib\transformation\file\index.js:333:39)
    at File.enter (C:\action-production\node_modules\babel-core\lib\transformation\file\metadata.js:26:32)
    at NodePath._call (C:\action-production\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (C:\action-production\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (C:\action-production\node_modules\babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (C:\action-production\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitMultiple (C:\action-production\node_modules\babel-traverse\lib\context.js:103:17)
    at TraversalContext.visit (C:\action-production\node_modules\babel-traverse\lib\context.js:190:19)
    at Function.traverse.node (C:\action-production\node_modules\babel-traverse\lib\index.js:114:17)
    at traverse (C:\action-production\node_modules\babel-traverse\lib\index.js:79:12)
    at NodePath.traverse (C:\action-production\node_modules\babel-traverse\lib\path\index.js:144:25)
    at File.getMetadata (C:\action-production\node_modules\babel-core\lib\transformation\file\index.js:211:17)
    at File._addAst (C:\action-production\node_modules\babel-core\lib\transformation\file\index.js:542:10)
    at File.addAst (C:\action-production\node_modules\babel-core\lib\transformation\file\index.js:547:10)
    at File.parseCode (C:\action-production\node_modules\babel-core\lib\transformation\file\index.js:613:10)
    at C:\action-production\node_modules\babel-core\lib\transformation\pipeline.js:49:12
    at File.wrap (C:\action-production\node_modules\babel-core\lib\transformation\file\index.js:574:16)
    at Pipeline.transform (C:\action-production\node_modules\babel-core\lib\transformation\pipeline.js:47:17)
    at Object.transformFileSync (C:\action-production\node_modules\babel-core\lib\api\node.js:138:10)
    at compile (C:\action-production\node_modules\babel-register\lib\node.js:118:20)
    at loader (C:\action-production\node_modules\babel-register\lib\node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (C:\action-production\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:/action-production/src/server/graphql/rootMutation.js:5:1)
    at Module._compile (module.js:570:32)
    at loader (C:\action-production\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\action-production\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
 @ ./universal/routes/index.js 30:23-72
 @ ./server/webpackEntry.js
`
I dont understand what is going on graphql is installed in node_modules. Do you have any idéas?

BTW: I am running Windows.

//Jonas

**Comment by alvestjo** [comment]
Hi again,

I tried to run the same code on a Ubuntu VM and it seem to work without problems. The above problem seem to be a Windows issue. I will continue to run on Ubuntu for now. 
//Jonas

**Comment by jordanh** [comment]
Thank you for reporting this! You're the first person we've heard from trying to use our codebase on Windows.

From the data you shared, it looks like ./server/utils/getCashaySchema.js cannot import the `graphql` module. I'm not quite certain why that isn't working.

If you figure it out, we'd love to know! I'm going to close this for now.

**Comment by ackernaut** [comment]
Hey there @alvestjo! We’d be very happy for you to join our growing dev community on Slack where we can continue to chat about the stack, issues, etc. [Parabol Developer Community](http://slackin.parabol.co/) Be sure and say “hello!” if ya join. 😄
