### ISSUE TITLE
With new user, getting ducks on /me/organizations/:orgId route [EP2: add-orgs] 

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#697]
## Issue - Bug

Reproduction steps:

1. Create new user
2. Navigate to team view
3. Click on trial expired modal

![image](https://cloud.githubusercontent.com/assets/103000/22567754/359da89e-e95f-11e6-96c5-77b2a1713cdc.png)

**Comment by jordanh** [comment]
From tip of branch today, a fresh exception.

Reproduction steps:

1. (delete user from auth0 dev instance)
2. Navigate to http://localhost:3000
3. Complete welcome wizard
4. Click on "Go to my account" on green banner

This is the exception:

```
DEBUG GraphQL Subscribe Error: organization [ { ReferenceError: user is not defined
      at _callee3$ (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/utils/authorization.js:88:36)
      at tryCatch (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/regenerator-runtime/runtime.js:63:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/regenerator-runtime/runtime.js:337:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/regenerator-runtime/runtime.js:96:21)
      at step (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/utils/authorization.js:20:191)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/utils/authorization.js:20:437
      at new Promise (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/core-js/modules/es6.promise.js:191:7)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/utils/authorization.js:20:99
      at getUserOrgDoc (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/utils/authorization.js:86:14)
      at _callee2$ (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/graphql/models/Organization/organizationSubscription.js:64:32)
      at tryCatch (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/regenerator-runtime/runtime.js:63:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/regenerator-runtime/runtime.js:337:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/regenerator-runtime/runtime.js:96:21)
      at step (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/graphql/models/Organization/organizationSubscription.js:29:191)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/graphql/models/Organization/organizationSubscription.js:29:437
      at new Promise (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/core-js/modules/es6.promise.js:191:7)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/graphql/models/Organization/organizationSubscription.js:29:99
      at resolve (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/graphql/models/Organization/organizationSubscription.js:59:82)
      at resolveOrError (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:473:12)
      at resolveField (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:459:16)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:273:18
      at Array.reduce (native)
      at executeFields (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:270:42)
      at executeOperation (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:211:10)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:119:13
      at new Promise (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/core-js/modules/es6.promise.js:191:7)
      at execute (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:118:10)
      at Promise.then.error.errors (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/graphql.js:58:36)
      at new Promise (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/core-js/modules/es6.promise.js:191:7)
      at graphql (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/graphql.js:51:10)
      at Emitter._callee$ (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/socketHandlers/scSubscribeHandler.js:66:28)
      at tryCatch (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/regenerator-runtime/runtime.js:63:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/regenerator-runtime/runtime.js:337:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/regenerator-runtime/runtime.js:96:21)
      at step (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/socketHandlers/scSubscribeHandler.js:29:191)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/socketHandlers/scSubscribeHandler.js:29:437
      at new Promise (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/core-js/modules/es6.promise.js:191:7)
      at Emitter.<anonymous> (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/socketHandlers/scSubscribeHandler.js:29:99)
      at Emitter.subscribeHandler (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/socketHandlers/scSubscribeHandler.js:49:3)
      at Emitter.emit (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/component-emitter/index.js:131:20)
      at Emitter.SCEmitter.emit (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/sc-emitter/index.js:40:26)
      at Emitter.SCSocket.emit (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/scsocket.js:303:30)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/scserver.js:218:16
      at addSubscription (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/sc-broker-cluster/index.js:590:17)
      at callback (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/sc-broker/index.js:321:26)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/sc-domain/index.js:31:16
      at new Promise (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/core-js/modules/es6.promise.js:191:7)
      at run (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/sc-domain/index.js:29:6)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/sc-domain/index.js:42:14
      at Socket.<anonymous> (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/sc-broker/index.js:231:11)
      at emitOne (events.js:96:13)
      at Socket.emit (events.js:188:7)
      at Socket.EventEmitter.emit (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/sc-domain/index.js:12:31)
      at Socket.<anonymous> (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/ncom/index.js:45:19)
      at emitOne (events.js:96:13)
      at Socket.emit (events.js:188:7)
      at Socket.EventEmitter.emit (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/sc-domain/index.js:12:31)
      at readableAddChunk (_stream_readable.js:177:18)
      at Socket.Readable.push (_stream_readable.js:135:10)
      at Pipe.onread (net.js:542:20)
    message: 'user is not defined',
    locations: [ [Object] ],
    path: [ 'organization' ] } ]
```

**Comment by jordanh** [comment]
I fixed the exception (committed to the `add-org-invites` branch https://github.com/ParabolInc/action/commit/88f46381becbf8adb2fc81f50896e0cd6e4a7b34).

The next thing I'm running into is the initial changes from the `organization` subscription isn't coming back.

Here is my `Organization` record:

```javascript
{
"activeUsers": [
"google-oauth2|112540584686400405659"
] ,
"createdAt": Sat Feb 04 2017 19:54:10 GMT+00:00 ,
"id":  "r1ovZnX_l" ,
"inactiveUsers": [ ],
"isTrial": true ,
"name":  "undefined's Org" ,
"stripeId":  "cus_A3gzfmByqnKHWc" ,
"stripeSubscriptionId":  "sub_A3gzxGFEnvxvVW" ,
"updatedAt": Sat Feb 04 2017 19:54:10 GMT+00:00 ,
"validUntil": Mon Mar 06 2017 19:54:11 GMT+00:00
}
```

I'm noticing that the changefeed setup by the `organization` subscription is looking for an array field called `orgUsers`. I _think_ the schema for this array is `{ id: <userId>, role: <roleConstant> }`, however, I don't see where this field is initialized. I _think_ it should be initialized within `createStripeOrg.js`. Is that right?

**Comment by jordanh** [comment]
The above seems right, I'm going to close this for now 😄
