### ISSUE TITLE
When reactivating user on team, exception hit [add-orgs]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#726]
## Issue - Bug

Steps to reproduce:

1. Create new team as user A
2. Invite new user B (causing `User` B record to be inserted in DB)
3. Accept invitation as new user B
4. Leave Team as user B
5. Re-add user B as user A via Team Settings

Observe exception:

```
DEBUG GraphQL Error: [ { ReferenceError: userId is not defined
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/graphql/models/Invitation/inviteTeamMembers/reactivateTeamMembers.js:31:17
      at Array.forEach (native)
      at _callee$ (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/graphql/models/Invitation/inviteTeamMembers/reactivateTeamMembers.js:23:22)
      at tryCatch (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/regenerator-runtime/runtime.js:337:22)
      at Generator.prototype.(anonymous function) [as next] (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/regenerator-runtime/runtime.js:96:21)
      at tryCatch (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/regenerator-runtime/runtime.js:279:24)
      at Generator.prototype.(anonymous function) [as next] (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/regenerator-runtime/runtime.js:96:21)
      at step (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/graphql/models/Invitation/inviteTeamMembers/reactivateTeamMembers.js:15:191)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/graphql/models/Invitation/inviteTeamMembers/reactivateTeamMembers.js:15:361
    message: 'userId is not defined',
    locations: [ [Object] ],
    path: [ 'inviteTeamMembers' ] } ]
```

**Comment by mattkrick** [comment]
i believe this to be fixed, please reopen if it's not
