### ISSUE TITLE
Migration failure [Epic 2]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#746]
## Issue - Bug

Hey 😎 🆒 😎  we're getting real close to being able to production deploy Epic 2. We got a few things to shake loose, it looks like.

Here's the first: an exception while migrating production data.

```
remote:        Creating a pool connected to dokku-rethinkdb-rethinkdb:28015        
remote:        [rethink-migrate] Connected        
remote:        [rethink-migrate]  ↑  up  ↑  20161125141100 addOrgs        
remote:        [rethink-migrate] Migration failed        
remote:        { Error: Invalid quantity: total amount (quantity * plan amount) must be no more than $999,999.99 USD        
remote:            at Constructor._Error (/app/node_modules/stripe/lib/Error.js:12:17)        
remote:            at Constructor (/app/node_modules/stripe/lib/utils.js:97:13)        
remote:            at Constructor (/app/node_modules/stripe/lib/utils.js:97:13)        
remote:            at Function.StripeError.generate (/app/node_modules/stripe/lib/Error.js:56:14)        
remote:            at IncomingMessage.<anonymous> (/app/node_modules/stripe/lib/StripeResource.js:137:39)        
remote:            at emitNone (events.js:91:20)        
remote:            at IncomingMessage.emit (events.js:186:7)        
remote:            at endReadableNT (_stream_readable.js:974:12)        
remote:            at _combinedTickCallback (internal/process/next_tick.js:74:11)        
remote:            at process._tickDomainCallback (internal/process/next_tick.js:122:9)        
remote:          type: 'StripeInvalidRequestError',        
remote:          stack: 'Error: Invalid quantity: total amount (quantity * plan amount) must be no more than $999,999.99 USD\n    at Constructor._Error (/app/node_modules/stripe/lib/Error.js:12:17)\n    at Constructor (/app/node_modules/stripe/lib/utils.js:97:13)\n    at Constructor (/app/node_modules/stripe/lib/utils.js:97:13)\n    at Function.StripeError.generate (/app/node_modules/stripe/lib/Error.js:56:14)\n    at IncomingMessage.<anonymous> (/app/node_modules/stripe/lib/StripeResource.js:137:39)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:186:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:122:9)',        
remote:          rawType: 'invalid_request_error',        
remote:          code: undefined,        
remote:          param: 'quantity',        
remote:          message: 'Invalid quantity: total amount (quantity * plan amount) must be no more than $999,999.99 USD',        
remote:          detail: undefined,        
remote:          raw:         
remote:           { type: 'invalid_request_error',        
remote:             message: 'Invalid quantity: total amount (quantity * plan amount) must be no more than $999,999.99 USD',        
remote:             param: 'quantity',        
remote:             statusCode: 400,        
remote:             requestId: 'req_ABwFV7C15zJmDT' },        
remote:          requestId: 'req_ABwFV7C15zJmDT',        
remote:          statusCode: 400 }        
remote:        Error: Invalid quantity: total amount (quantity * plan amount) must be no more than $999,999.99 USD        
remote:            at Constructor._Error (/app/node_modules/stripe/lib/Error.js:12:17)        
remote:            at Constructor (/app/node_modules/stripe/lib/utils.js:97:13)        
remote:            at Constructor (/app/node_modules/stripe/lib/utils.js:97:13)        
remote:            at Function.StripeError.generate (/app/node_modules/stripe/lib/Error.js:56:14)        
remote:            at IncomingMessage.<anonymous> (/app/node_modules/stripe/lib/StripeResource.js:137:39)        
remote:            at emitNone (events.js:91:20)        
remote:            at IncomingMessage.emit (events.js:186:7)        
remote:            at endReadableNT (_stream_readable.js:974:12)        
remote:            at _combinedTickCallback (internal/process/next_tick.js:74:11)        
remote:            at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

See also: https://circleci.com/gh/ParabolInc/action/1893

- **OS:** Linux

**Comment by jordanh** [comment]
That was it! The migrations run now. Woot!
