### ISSUE TITLE
Fix Circle CI migrations

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/action#761]
@jordanh should we be migrating actionTesting in CircleCI instead of actionDevelopment? How were you doing it before this merge? Did i goof something up? Also, if we move to just using `NODE_ENV=test` then we could a nice bypass on the stripe migration so it doesn't yell so much. _Not_ an error, but not pretty:
```
will migrate up all
[rethink-migrate] Connecting to database
Creating a pool connected to localhost:28015
[rethink-migrate] Creating database actionDevelopment
[rethink-migrate] Connected
[rethink-migrate]  ↑  up  ↑  20160715095300 initialize
[rethink-migrate]  ↑  up  ↑  20160722161700 meeting
[rethink-migrate]  ↑  up  ↑  20160726160100 mockTeam
[rethink-migrate]  ↑  up  ↑  20160906105600 add-agenda-ids
[rethink-migrate]  ↑  up  ↑  20160923154400 project-archive
[rethink-migrate]  ↑  up  ↑  20161013161900 project-history
[rethink-migrate]  ↑  up  ↑  20161105214300 invitation
[rethink-migrate]  ↑  up  ↑  20161114214000 allFacilitators
[rethink-migrate]  ↑  up  ↑  20161121091100 addTmsOnMock
[rethink-migrate]  ↑  up  ↑  20161125141100 addOrgs
[rethink-migrate] Migration failed
{ Error: You did not provide an API key, though you did set your Authorization header to "null". Using Bearer auth, your Authorization header should look something like 'Authorization: Bearer YOUR_SECRET_KEY'. See https://stripe.com/docs/api#authentication for details, or we can help at https://support.stripe.com/.
    at Constructor._Error (/home/ubuntu/action/node_modules/stripe/lib/Error.js:12:17)
    at Constructor (/home/ubuntu/action/node_modules/stripe/lib/utils.js:97:13)
    at Constructor (/home/ubuntu/action/node_modules/stripe/lib/utils.js:97:13)
    at IncomingMessage.<anonymous> (/home/ubuntu/action/node_modules/stripe/lib/StripeResource.js:131:21)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  type: 'StripeAuthenticationError',
```

**Comment by mattkrick** [comment]
fun fact: the tests on master are all failing, it's just not throwing a code 1 😃 

```
 FAIL  src/universal/redux/__tests__/AuthEngine-tests.js
  ● Test suite failed to run
```

**Comment by mattkrick** [comment]
hey it works
