### ISSUE TITLE
Cannot approve new user into org [Epic2]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#765]
## Issue - Bug

![image](https://cloud.githubusercontent.com/assets/103000/23438204/facdbd00-fdde-11e6-87c9-52af24cad9a0.png)

When I press the `Accept` button, nothing appears to happen. However, when I view the server logs I see the following exception:

```
2017-02-28T22:55:16.483577853Z app[web.1]: DEBUG GraphQL Error: [ { Error: {"_error":"Unauthorized to view details for team matt+a1@parabol.co with token {\"tms\":[\"BJjaRrf1l\",\"BJpGw2Wcg\",\"BkuB7boHx\",\"Byw8SozA\",\"HJIVBjGA\",\"HJQi_uMUl\",\"HJZsjiuge\",\"HyH1xnRdl\",\"SJ8JvS-Jx\",\"ryrERv6xg\"],\"iss\":\"https://parabol.auth0.com/\",\"sub\":\"google-oauth2|112540584686400405659\",\"aud\":\"d3kxpUVVTk4rEEzRnRtbigAMReRXI71T\",\"iat\":1488204666}"}
2017-02-28T22:55:16.483660885Z app[web.1]:       at errorObj (/app/src/server/utils/utils.js:7:32)
2017-02-28T22:55:16.483670534Z app[web.1]:       at _callee$ (/app/src/server/utils/authorization.js:55:13)
2017-02-28T22:55:16.483675472Z app[web.1]:       at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:63:40)
2017-02-28T22:55:16.483680312Z app[web.1]:       at Generator.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:337:22)
2017-02-28T22:55:16.483687244Z app[web.1]:       at Generator.prototype.(anonymous function) [as next] (/app/node_modules/regenerator-runtime/runtime.js:96:21)
2017-02-28T22:55:16.483692099Z app[web.1]:       at step (/app/src/server/utils/authorization.js:20:191)
2017-02-28T22:55:16.483696819Z app[web.1]:       at /app/src/server/utils/authorization.js:20:361
2017-02-28T22:55:16.483701547Z app[web.1]:     message: '{"_error":"Unauthorized to view details for team matt+a1@parabol.co with token {\\"tms\\":[\\"BJjaRrf1l\\",\\"BJpGw2Wcg\\",\\"BkuB7boHx\\",\\"Byw8SozA\\",\\"HJIVBjGA\\",\\"HJQi_uMUl\\",\\"HJZsjiuge\\",\\"HyH1xnRdl\\",\\"SJ8JvS-Jx\\",\\"ryrERv6xg\\"],\\"iss\\":\\"https://parabol.auth0.com/\\",\\"sub\\":\\"google-oauth2|112540584686400405659\\",\\"aud\\":\\"d3kxpUVVTk4rEEzRnRtbigAMReRXI71T\\",\\"iat\\":1488204666}"}',
2017-02-28T22:55:16.483712085Z app[web.1]:     locations: [ [Object] ],
2017-02-28T22:55:16.483716522Z app[web.1]:     path: [ 'inviteTeamMembers' ] } ]
```

- **OS:** OSX
- **Browser:** Chrome

**Comment by jordanh** [comment]
Decline seems to work just fine tho :wink:

**Comment by mattkrick** [comment]
fixed on dnd-sortOrder
