### ISSUE TITLE
Server exception on creating new project [dnd-sortOrder]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#777]
## Issue - Bug

Reproduction steps:

1. Start new meeting
1. Add at least one agenda item
1. During first agenda item, click "New Team Project"
1. Observe below exception

```
DEBUG GraphQL Error: [ { GraphQLError
      at getVariableValues (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/values.js:78:15)
      at buildExecutionContext (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:186:54)
      at execute (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:109:17)
      at Promise.then.error.errors (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/graphql.js:58:36)
      at graphql (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/graphql.js:51:10)
      at SCSocket.graphQLHandler (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/socketHandlers/scGraphQLHandler.js:27:26)
      at SCSocket.Emitter.emit (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/sc-emitter/node_modules/component-emitter/index.js:131:20)
      at SCSocket.SCEmitter.emit (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/sc-emitter/index.js:40:26)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/scsocket.js:126:44
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/scserver.js:739:11
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:396:18
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:905:11
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:396:18
      at replenish (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:866:27)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:882:13
      at _asyncMap (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:898:7)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:888:18
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:932:18
      at Object.<anonymous> (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:363:22)
      at Object.<anonymous> (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:355:14)
      at Object.<anonymous> (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:338:29)
      at Object.<anonymous> (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:368:25)
      at Object.applyEachSeries (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:339:29)
      at SCServer._passThroughMiddleware (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/scserver.js:726:11)
      at SCServer.verifyInboundEvent (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/scserver.js:619:8)
      at WebSocket.internalOnMessage (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/scsocket.js:109:23)
      at onServerMessage (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/uws/uws.js:14:15)
    message: 'Variable "$newProject" got invalid value {"id":"team123::B1Bi1fYqx","status":"active","teamMemberId":"auth0|58a861e682b0ca077463c577::team123","sortOrder":0,"agendaId":"team123::HJ7ikMFqe"}.\nIn field "agendaId": Unknown field.',
    locations: [ [Object] ],
    path: undefined } ]
(node:72622) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at SCSocket.graphQLHandler (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/socketHandlers/scGraphQLHandler.js:31:36)
    at runMicrotasksCallback (internal/process/next_tick.js:58:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
DEBUG GraphQL Error: [ { GraphQLError
      at getVariableValues (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/values.js:78:15)
      at buildExecutionContext (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:186:54)
      at execute (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:109:17)
      at Promise.then.error.errors (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/graphql.js:58:36)
      at graphql (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/graphql.js:51:10)
      at SCSocket.graphQLHandler (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/socketHandlers/scGraphQLHandler.js:27:26)
      at SCSocket.Emitter.emit (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/sc-emitter/node_modules/component-emitter/index.js:131:20)
      at SCSocket.SCEmitter.emit (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/sc-emitter/index.js:40:26)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/scsocket.js:126:44
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/scserver.js:739:11
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:396:18
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:905:11
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:396:18
      at replenish (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:866:27)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:882:13
      at _asyncMap (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:898:7)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:888:18
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:932:18
      at Object.<anonymous> (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:363:22)
      at Object.<anonymous> (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:355:14)
      at Object.<anonymous> (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:338:29)
      at Object.<anonymous> (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:368:25)
      at Object.applyEachSeries (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:339:29)
      at SCServer._passThroughMiddleware (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/scserver.js:726:11)
      at SCServer.verifyInboundEvent (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/scserver.js:619:8)
      at WebSocket.internalOnMessage (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/scsocket.js:109:23)
      at onServerMessage (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/uws/uws.js:14:15)
    message: 'Variable "$newProject" got invalid value {"id":"team123::Sy831MKqg","status":"active","teamMemberId":"auth0|58a861e682b0ca077463c577::team123","sortOrder":0,"agendaId":"team123::HJ7ikMFqe"}.\nIn field "agendaId": Unknown field.',
    locations: [ [Object] ],
    path: undefined } ]
(node:72622) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at SCSocket.graphQLHandler (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/socketHandlers/scGraphQLHandler.js:31:36)
    at runMicrotasksCallback (internal/process/next_tick.js:58:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
DEBUG GraphQL Error: [ { GraphQLError
      at getVariableValues (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/values.js:78:15)
      at buildExecutionContext (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:186:54)
      at execute (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:109:17)
      at Promise.then.error.errors (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/graphql.js:58:36)
      at graphql (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/graphql.js:51:10)
      at SCSocket.graphQLHandler (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/socketHandlers/scGraphQLHandler.js:27:26)
      at SCSocket.Emitter.emit (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/sc-emitter/node_modules/component-emitter/index.js:131:20)
      at SCSocket.SCEmitter.emit (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/sc-emitter/index.js:40:26)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/scsocket.js:126:44
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/scserver.js:739:11
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:396:18
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:905:11
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:396:18
      at replenish (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:866:27)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:882:13
      at _asyncMap (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:898:7)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:888:18
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:932:18
      at Object.<anonymous> (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:363:22)
      at Object.<anonymous> (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:355:14)
      at Object.<anonymous> (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:338:29)
      at Object.<anonymous> (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:368:25)
      at Object.applyEachSeries (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/node_modules/async/dist/async.js:339:29)
      at SCServer._passThroughMiddleware (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/scserver.js:726:11)
      at SCServer.verifyInboundEvent (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/scserver.js:619:8)
      at WebSocket.internalOnMessage (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/socketcluster-server/scsocket.js:109:23)
      at onServerMessage (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/uws/uws.js:14:15)
    message: 'Variable "$newProject" got invalid value {"id":"team123::ByUaJfY9g","status":"active","teamMemberId":"auth0|58a861e682b0ca077463c577::team123","sortOrder":0,"agendaId":"team123::HJ7ikMFqe"}.\nIn field "agendaId": Unknown field.',
    locations: [ [Object] ],
    path: undefined } ]
(node:72622) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at SCSocket.graphQLHandler (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/socketHandlers/scGraphQLHandler.js:31:36)
    at runMicrotasksCallback (internal/process/next_tick.js:58:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by jordanh** [comment]
Verified!
