### ISSUE TITLE
Server exception on meetingSummary [dnd-sortOrder]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#778]
## Issue - Bug

Repro steps:

1. Login as `jordan@prbl.co`
2. Start meeting on `Parabol` team
3. Proceed through meeting:
   1. Create one agenda item
   2. Create two new output projects (1 for terry, 1 for jordan)
4. End meeting

Observe exception:

```
DEBUG GraphQL Error: [ { Error: Expected a value of type "ProjectStatus" but received: active
      at completeLeafValue (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:639:11)
      at completeValue (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:586:12)
      at completeValueWithLocatedError (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:517:21)
      at completeValueCatchingError (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:493:21)
      at resolveField (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:461:10)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:273:18
      at Array.reduce (native)
      at executeFields (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:270:42)
      at completeObjectValue (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:688:10)
      at completeValue (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:597:12)
      at completeValueWithLocatedError (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:517:21)
      at completeValueCatchingError (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:493:21)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:620:25
      at Array.forEach (native)
      at forEach (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/iterall/index.js:272:25)
      at completeListValue (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:616:24)
      at completeValue (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:580:12)
      at completeValueWithLocatedError (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:517:21)
      at completeValueCatchingError (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:493:21)
      at resolveField (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:461:10)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:273:18
      at Array.reduce (native)
      at executeFields (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:270:42)
      at completeObjectValue (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:688:10)
      at completeValue (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:597:12)
      at completeValueWithLocatedError (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:517:21)
      at completeValueCatchingError (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:493:21)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:620:25
      at Array.forEach (native)
      at forEach (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/iterall/index.js:272:25)
      at completeListValue (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:616:24)
      at completeValue (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:580:12)
      at completeValueWithLocatedError (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:517:21)
      at completeValueCatchingError (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:493:21)
      at resolveField (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:461:10)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:273:18
      at Array.reduce (native)
      at executeFields (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:270:42)
      at completeObjectValue (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:688:10)
      at completeValue (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:597:12)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:554:14
    message: 'Expected a value of type "ProjectStatus" but received: active',
    locations: [ [Object] ],
    path: [ 'summarizeMeeting', 'invitees', 0, 'projects', 0, 'status' ] },
  { Error: Expected a value of type "ProjectStatus" but received: active
      at completeLeafValue (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:639:11)
      at completeValue (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:586:12)
      at completeValueWithLocatedError (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:517:21)
      at completeValueCatchingError (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:493:21)
      at resolveField (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:461:10)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:273:18
      at Array.reduce (native)
      at executeFields (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:270:42)
      at completeObjectValue (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:688:10)
      at completeValue (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:597:12)
      at completeValueWithLocatedError (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:517:21)
      at completeValueCatchingError (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:493:21)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:620:25
      at Array.forEach (native)
      at forEach (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/iterall/index.js:272:25)
      at completeListValue (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:616:24)
      at completeValue (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:580:12)
      at completeValueWithLocatedError (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:517:21)
      at completeValueCatchingError (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:493:21)
      at resolveField (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:461:10)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:273:18
      at Array.reduce (native)
      at executeFields (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:270:42)
      at completeObjectValue (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:688:10)
      at completeValue (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:597:12)
      at completeValueWithLocatedError (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:517:21)
      at completeValueCatchingError (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:493:21)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:620:25
      at Array.forEach (native)
      at forEach (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/iterall/index.js:272:25)
      at completeListValue (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:616:24)
      at completeValue (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:580:12)
      at completeValueWithLocatedError (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:517:21)
      at completeValueCatchingError (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:493:21)
      at resolveField (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:461:10)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:273:18
      at Array.reduce (native)
      at executeFields (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:270:42)
      at completeObjectValue (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:688:10)
      at completeValue (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:597:12)
      at /Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/graphql/execution/execute.js:554:14
    message: 'Expected a value of type "ProjectStatus" but received: active',
    locations: [ [Object] ],
    path: [ 'summarizeMeeting', 'invitees', 3, 'projects', 0, 'status' ] } ]
Warning: Unknown prop `align` on <table> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in table
    in Layout
Warning: Failed prop type: Always include the `height` and `width` attributes of your <img> as integers. See https://www.campaignmonitor.com/resources/will-it-work/guidelines/
    in Img
Warning: Failed prop type: Relative src URLs can break (i.e. if recipients are outside the company network) and make your content unavailable to view.
    in Img
Warning: Unknown props `border`, `tagName` on <table> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in table (created by Table)
    in Table
mailgun: no API key, so not sending the following:
    From: 
    To: , taya@prbl.co, terry@prbl.co, matt@prbl.co
    Subject: Action Meeting Summary from Parabol
    Body: Hello Parabol! As a team you discussed 1 Agenda Items 
resulting in 2 New Projects 
and 0 New Actions.
```

- **OS:** OSX
- **Browser:** Chrome

**Comment by mattkrick** [comment]
well that was WEIRD. i have no idea why my helper function stopped working, but i replaced it throughout and we're back to good. nice find!

**Comment by jordanh** [comment]
The fun of testing! Shall I run another pass now?

**Comment by mattkrick** [comment]
hitting refresh on the summary should suffice :smile:

**Comment by jordanh** [comment]
Verified fix!
