### ISSUE TITLE
Exception on new (test) team member invitation [dnd-sortOrder]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#779]
## Issue - Bug

This might be something specific to how we're initializing our mock users for development. I'm using `jordan@prbl.io`.

Repro steps:

1. Login as `jordan@prbl.co`
1. Click on `Engineering` team
1. Click on `Team Settings`
1. Invite a new users, such as `scott@prbl.co`

Observe exception:

```
DEBUG GraphQL Error: [ { ReqlRuntimeError: Cannot perform bracket on a non-object non-sequence `null` in:
  r.expr(["scott@prbl.co"]).do(function(var_29) {
      return {
          inviteEmails: r.table("Invitation").getAll(r.args(var_29), {
              index: "email"
          }).filter(function(var_30) {
              return var_30("tokenExpiration").ge(r.epochTime(1488745645308))
          })("email").coerceTo("array"),
          teamMembers: r.table("TeamMember").getAll("team456", {
              index: "teamId"
          }).merge(function(var_31) {
              return {
                  userOrgs: r.table("User").get(var_31("userId"))("userOrgs")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^            
              }
          }).coerceTo("array")
      }
  })
  
      at Connection._processResponse (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/rethinkdbdash/lib/connection.js:395:15)
      at Socket.<anonymous> (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/rethinkdbdash/lib/connection.js:201:14)
      at emitOne (events.js:96:13)
      at Socket.emit (events.js:189:7)
      at Socket.EventEmitter.emit (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/sc-domain/index.js:12:31)
      at readableAddChunk (_stream_readable.js:176:18)
      at Socket.Readable.push (_stream_readable.js:134:10)
      at TCP.onread (net.js:551:20)
  From previous event:
      at Function.Term.run (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/rethinkdbdash/lib/term.js:142:15)
      at Function.Term.then (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/node_modules/rethinkdbdash/lib/term.js:2876:15)
    message: 'Cannot perform bracket on a non-object non-sequence `null` in:\nr.expr(["scott@prbl.co"]).do(function(var_29) {\n    return {\n        inviteEmails: r.table("Invitation").getAll(r.args(var_29), {\n            index: "email"\n        }).filter(function(var_30) {\n            return var_30("tokenExpiration").ge(r.epochTime(1488745645308))\n        })("email").coerceTo("array"),\n        teamMembers: r.table("TeamMember").getAll("team456", {\n            index: "teamId"\n        }).merge(function(var_31) {\n            return {\n                userOrgs: r.table("User").get(var_31("userId"))("userOrgs")\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^            \n            }\n        }).coerceTo("array")\n    }\n})\n',
    locations: [ [Object] ],
    path: [ 'inviteTeamMembers' ] } ]
```

**Comment by mattkrick** [comment]
ah yeah, that's because jordan@prbl.co got borked in auth0 somehow & then , same thing happened to taya. this error is essentially saying that it can't find the user jordan, even though the team member exists. if this ever coudl happen, we'd want it to err.

in the future, let's write a helper that adds mock folks to auth0 and stripe so we don't can get the mock people out of the DB migrations.

**Comment by jordanh** [comment]
For now I'd like to fix our mocks. Can you see how it's borked? I think the ids match between what's in the migration/database and what's up on auth0...

**Comment by jordanh** [comment]
Verified fix!
