### ISSUE TITLE
Server crash and duckies when loading migrated orgs [Epic2]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#783]
## Issue - Bug

Now we're getting into the fun stuff.

Repro steps:

1. Login as jordan@parabol.co (impersonate: `google-oauth2|112540584686400405659`)
2. Go to settings->organizations (of note, first time this loaded it took a _long_ time to resolve, 20 seconds?)
3. Click on `Settings and Billing`
4. Observe duckies

Server exceptions is:

```
2017-03-06T05:47:52.006902596Z app[web.1]: 1488779272006 - Origin: Worker (PID 651)
2017-03-06T05:47:52.006921855Z app[web.1]:    [Error] ReqlRuntimeError
2017-03-06T05:47:52.006926353Z app[web.1]:     at Connection._processResponse (/app/node_modules/rethinkdbdash/lib/connection.js:395:15)
2017-03-06T05:47:52.006930290Z app[web.1]:     at Socket.<anonymous> (/app/node_modules/rethinkdbdash/lib/connection.js:201:14)
2017-03-06T05:47:52.006934780Z app[web.1]:     at emitOne (events.js:96:13)
2017-03-06T05:47:52.006938365Z app[web.1]:     at Socket.emit (events.js:189:7)
2017-03-06T05:47:52.006942031Z app[web.1]:     at Socket.EventEmitter.emit (/app/node_modules/sc-domain/index.js:12:31)
2017-03-06T05:47:52.006945726Z app[web.1]:     at readableAddChunk (_stream_readable.js:176:18)
2017-03-06T05:47:52.006949435Z app[web.1]:     at Socket.Readable.push (_stream_readable.js:134:10)
2017-03-06T05:47:52.006953065Z app[web.1]:     at TCP.onread (net.js:551:20)
```

...unhelpfully.

**Comment by mattkrick** [comment]
oddly enough, i didn't get this error, however i did get another:

```
[redux-raven-middleware] Reporting error to Sentry: Error: Supplying pagination cursors to cashay is not supported. [object Object]
    at y (https://action-files.parabol.co/staging/build/v0.16.3/app_9ed5641e9d1bee5e5cec.js:836:289)
    at r (https://action-files.parabol.co/staging/build/v0.16.3/app_9ed5641e9d1bee5e5cec.js:836:593)
    at p (https://action-files.parabol.co/staging/build/v0.16.3/app_9ed5641e9d1bee5e5cec.js:814:746)
    at y (https://action-files.parabol.co/staging/build/v0.16.3/app_9ed5641e9d1bee5e5cec.js:814:1668)
```

I'll fix up the error I got & we can go from there...

**Comment by jordanh** [comment]
Oh odd. Was this on your user or my user?

**Comment by jordanh** [comment]
Oh how interesting. Now this link is loading for me: https://action-staging.parabol.co/me/organizations/Sk1mZJ-E9ce! I wonder if the `action-chronos` task populated something in the database that was missing before?

**Comment by jordanh** [comment]
You know what's cool @mattkrick? The new map files work on sentry automatically. Check it: https://sentry.io/parabol/action-staging/issues/229937733/

**Comment by mattkrick** [comment]
Sentry is just the best

**Comment by mattkrick** [comment]
oh man, this is just weird.
i copied this over the staging DB.
moved it to actionDevelopment.
could not reproduce.
i'm wondering, is there any chance that we're using an older version of cashay?

reproducing in production mode locally leads to failing to fetch the resources so i can't load it:
![screen shot 2017-03-06 at 7 06 53 pm](https://cloud.githubusercontent.com/assets/5514175/23640079/1fc1f250-02a0-11e7-8d82-864d98bfe434.png)

**Comment by jordanh** [comment]
I don't think there is any possibility it is using an older version of Cashay, unless there are changes that weren't published 👅 

On using production mode locally... You should be able to comment out the CDN vars in your .env and rebuild, no?

**Comment by mattkrick** [comment]
oo ill try that now.

without knowing 100% the cause of it, i think i have a guess--
it's because the org document has a credit card object in it.
and that creditcard field is `null` instead of an object if no credit card exists.
cashay expects an object, but receives `null`, so it flags the query as incomplete, which causes a refetch every time the `cashay.query`is called. essentially, the query never completes!

there are a few ways to fix this, from easiest to hardest:
- keep the credit card object on the org document & just remove the fields inside it
- tell cashay to use `undefined` as a placeholder instead of `null`
- rewrite cashay to use static queries so we don't even have to mess around with diffs
