### ISSUE TITLE
 No such customer exception [Epic2]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#793]
## Issue - Bug

Reproduction steps:

1. Impersonate jordan.husney@google.com user`google-oauth2|112540584686400405659`
1. Navigate to User Hub->Organizations->Jordan's Org->Settings and Billing
1. Observe invoice list does not load

Exception:

```
2017-03-10T03:11:53.559765877Z app[web.1]: DEBUG GraphQL Error: [ { Error: No such customer: cus_AEdDLtDunq0MQ5
2017-03-10T03:11:53.559870355Z app[web.1]:       at Constructor._Error (/app/node_modules/stripe/lib/Error.js:12:17)
2017-03-10T03:11:53.559877714Z app[web.1]:       at Constructor (/app/node_modules/stripe/lib/utils.js:97:13)
2017-03-10T03:11:53.559882012Z app[web.1]:       at Constructor (/app/node_modules/stripe/lib/utils.js:97:13)
2017-03-10T03:11:53.559886135Z app[web.1]:       at Function.StripeError.generate (/app/node_modules/stripe/lib/Error.js:56:14)
2017-03-10T03:11:53.559890377Z app[web.1]:       at IncomingMessage.<anonymous> (/app/node_modules/stripe/lib/StripeResource.js:137:39)
2017-03-10T03:11:53.559899592Z app[web.1]:       at emitNone (events.js:91:20)
2017-03-10T03:11:53.559903902Z app[web.1]:       at IncomingMessage.emit (events.js:186:7)
2017-03-10T03:11:53.559907950Z app[web.1]:       at IncomingMessage.EventEmitter.emit (/app/node_modules/sc-domain/index.js:12:31)
2017-03-10T03:11:53.559912407Z app[web.1]:       at endReadableNT (_stream_readable.js:974:12)
2017-03-10T03:11:53.559916529Z app[web.1]:       at _combinedTickCallback (internal/process/next_tick.js:74:11)
2017-03-10T03:11:53.559920750Z app[web.1]:       at process._tickDomainCallback (internal/process/next_tick.js:122:9)
2017-03-10T03:11:53.559924897Z app[web.1]:     message: 'No such customer: cus_AEdDLtDunq0MQ5',
2017-03-10T03:11:53.559929150Z app[web.1]:     locations: [ [Object] ],
2017-03-10T03:11:53.559933182Z app[web.1]:     path: [ 'invoiceList' ] } ]
```

**Comment by mattkrick** [comment]
this was a problem with the invoiceList query, fixed in the unit test branch!
