### ISSUE TITLE
Server exception on viewing of invoice estimation

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#925]
## Issue - Bug

This occurred after I set up a team for new friends at Alchemist.

URL was: https://action.parabol.co/invoice/upcoming_BJljWBrT6g

```
2017-04-16T01:51:40.062280940Z app[web.1]: (node:232) Error: {"_error":"No such invoiceitem: SkdvrB6Tl"}
2017-04-16T01:51:40.062323825Z app[web.1]:     at errorObj (/app/src/server/utils/utils.js:7:34)
2017-04-16T01:51:40.062330597Z app[web.1]:     at _callee$ (/app/src/server/billing/stripe.js:12:11)
2017-04-16T01:51:40.062334700Z app[web.1]:     at tryCatch (/app/node_modules/cashay/node_modules/regenerator-runtime/runtime.js:63:40)
2017-04-16T01:51:40.062353197Z app[web.1]:     at Generator.invoke [as _invoke] (/app/node_modules/cashay/node_modules/regenerator-runtime/runtime.js:337:22)
2017-04-16T01:51:40.062357598Z app[web.1]:     at Generator.prototype.(anonymous function) [as throw] (/app/node_modules/cashay/node_modules/regenerator-runtime/runtime.js:96:21)
2017-04-16T01:51:40.062361768Z app[web.1]:     at step (/app/src/server/billing/stripe.js:21:191)
2017-04-16T01:51:40.062365592Z app[web.1]:     at /app/src/server/billing/stripe.js:21:402
```

**Comment by jordanh** [comment]
Been a long time since we've seen this one. Iceboxing.
