### ISSUE TITLE
Unable to proceed beyond check-in round [add-tags]

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/action#953]
## Issue - Bug

Repro steps:

1. Start a meeting with 2 participants
2. Navigate and proceed through check-in round

Observe server exception:

```
DEBUG GraphQL Error: [ { Error: {"_error":"this must be called from a websocket"}
      at errorObj (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/utils/utils.js:7:34)
      at requireWebsocket (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/utils/authorization.js:97:11)
      at _callee$ (/Users/jordanhusney/Source/Repositories/github.com/Parabol/action.git/src/server/graphql/models/TeamMember/teamMemberMutation.js:46:7)
...
```

- **OS:** OSX
- **Browser:** Chrome

**Comment by mattkrick** [comment]
is it possible that you lost your websocket connection by restarting the server or making a change to the code without refreshing the page? 

if you can reproduce this, can you tell me if the `checkIn` mutation is sent via websocket or XHR?

**Comment by jordanh** [comment]
I don't think so. I'm testing locally and making no changes to the source. Have you tried to repro it locally? If you can't repro, I'll investigate a bit more thoroughly here...

**Comment by mattkrick** [comment]
still can't repro locally, i'll push to staging & see if we can find it there

**Comment by jordanh** [comment]
Doh! This was on my end. I didn't have redis running. 😬
